In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sudhanvahg/indian-crimes-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'indian-crimes-dataset' dataset.
Path to dataset files: /kaggle/input/indian-crimes-dataset

In [3]:
path="/kaggle/input/indian-crimes-dataset"

In [5]:
import pandas as pd
df=pd.read_csv(path+"/crime_dataset_india.csv")

In [6]:
df.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
0,1,02-01-2020 00:00,01-01-2020 00:00,01-01-2020 01:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
1,2,01-01-2020 19:00,01-01-2020 01:00,01-01-2020 06:26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaN
2,3,02-01-2020 05:00,01-01-2020 02:00,01-01-2020 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
3,4,01-01-2020 05:00,01-01-2020 03:00,01-01-2020 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 05:00
4,5,01-01-2020 21:00,01-01-2020 04:00,01-01-2020 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21:00

In [7]:
df.sample(15)

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
13819,13820,01-08-2021 12:00,07-29-2021 19:00,29-07-2021 23:10,Delhi,161,ROBBERY,40,F,Explosives,Violent Crime,3,Yes,11-12-2021 12:00
14140,14141,12-08-2021 16:00,08-12-2021 04:00,12-08-2021 21:03,Ghaziabad,330,FIREARM OFFENSE,66,F,Knife,Fire Accident,3,Yes,03-09-2021 16:00
27513,27514,22-02-2023 01:00,02-20-2023 09:00,20-02-2023 18:38,Chennai,586,SHOPLIFTING,58,X,NaN,Other Crime,18,Yes,03-04-2023 01:00
17898,17899,18-01-2022 05:00,01-15-2022 18:00,15-01-2022 23:45,Delhi,595,PUBLIC INTOXICATION,34,X,Poison,Other Crime,15,No,NaN
400,401,18-01-2020 16:00,01-17-2020 16:00,17-01-2020 19:49,Meerut,567,DRUG OFFENSE,66,F,Knife,Other Crime,3,No,NaN
39086,39087,19-06-2024 10:00,06-16-2024 14:00,16-06-2024 17:08,Surat,410,KIDNAPPING,43,F,Poison,Other Crime,4,No,NaN
3255,3256,18-05-2020 09:00,05-15-2020 15:00,16-05-2020 02:43,Surat,425,FRAUD,79,F,Explosives,Other Crime,14,No,NaN
36993,36994,22-03-2024 11:00,03-21-2024 09:00,22-03-2024 04:13,Lucknow,136,TRAFFIC VIOLATION,16,F,Other,Traffic Fatality,3,No,NaN
33760,33761,09-11-2023 12:00,11-07-2023 16:00,08-11-2023 01:36,Delhi,582,COUNTERFEITING,64,F,Explosives,Other Crime,14,No,NaN
36024,36025,10-02-2024 05:00,02-10-2024 00:00,10-02-2024 20:24,Pune,433,ROBBERY,68,M,Knife,Violent Crime,12,No,NaN
15422,15423,07-10-2021 08:00,10-04-2021 14:00,05-10-2021 11:02,Kolkata,183,ROBBERY,76,F,Other,Violent Crime,13,No,NaN
27838,27839,06-03-2023 07:00,03-05-2023 22:00,06-03-2023 11:12,Kolkata,385,ARSON,64,F,Poison,Fire Accident,13,No,NaN
14244,14245,16-08-2021 16:00,08-16-2021 12:00,17-08-2021 08:18,Hyderabad,233,DRUG OFFENSE,33,F,Knife,Other Crime,8,Yes,15-10-2021 16:00
15050,15051,20-09-2021 22:00,09-19-2021 02:00,19-09-2021 18:25,Ludhiana,175,ILLEGAL POSSESSION,14,F,Blunt Object,Other Crime,10,Yes,17-10-2021 22:00
23351,23352,02-09-2022 09:00,08-30-2022 23:00,31-08-2022 07:22,Chennai,459,DRUG OFFENSE,57,F,Blunt Object,Other Crime,10,No,NaN

In [8]:
df.memory_usage()

Index                    132
Report Number         321280
Date Reported         321280
Date of Occurrence    321280
Time of Occurrence    321280
City                  321280
Crime Code            321280
Crime Description     321280
Victim Age            321280
Victim Gender         321280
Weapon Used           321280
Crime Domain          321280
Police Deployed       321280
Case Closed           321280
Date Case Closed      321280
dtype: int64

In [9]:
df['City'].value_counts().head(10)

City
Delhi        5400
Mumbai       4415
Bangalore    3588
Hyderabad    2881
Kolkata      2518
Chennai      2493
Pune         2212
Ahmedabad    1817
Jaipur       1479
Lucknow      1456
Name: count, dtype: int64

In [10]:
df["Crime Description"].value_counts()

Crime Description
BURGLARY               1980
VANDALISM              1975
FRAUD                  1965
DOMESTIC VIOLENCE      1932
FIREARM OFFENSE        1931
ROBBERY                1928
KIDNAPPING             1920
IDENTITY THEFT         1918
SEXUAL ASSAULT         1917
ASSAULT                1915
TRAFFIC VIOLATION      1915
PUBLIC INTOXICATION    1912
HOMICIDE               1909
CYBERCRIME             1899
ILLEGAL POSSESSION     1895
ARSON                  1894
DRUG OFFENSE           1890
EXTORTION              1873
COUNTERFEITING         1871
VEHICLE - STOLEN       1862
SHOPLIFTING            1859
Name: count, dtype: int64

In [12]:
df['City'].value_counts().head()

City
Delhi        5400
Mumbai       4415
Bangalore    3588
Hyderabad    2881
Kolkata      2518
Name: count, dtype: int64

In [13]:
df[
    df['Crime Description']=="SHOPLIFTING"
]

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
22,23,02-01-2020 10:00,01-01-2020 22:00,01-01-2020 22:03,Jaipur,507,SHOPLIFTING,69,F,Blunt Object,Other Crime,13,No,NaN
37,38,04-01-2020 05:00,01-02-2020 13:00,02-01-2020 18:04,Varanasi,280,SHOPLIFTING,22,F,Explosives,Other Crime,14,No,NaN
59,60,05-01-2020 18:00,01-03-2020 11:00,04-01-2020 05:33,Thane,352,SHOPLIFTING,53,F,Other,Other Crime,6,Yes,31-03-2020 18:00
60,61,03-01-2020 22:00,01-03-2020 12:00,03-01-2020 15:04,Mumbai,196,SHOPLIFTING,16,M,Poison,Other Crime,10,No,NaN
128,129,09-01-2020 04:00,01-06-2020 08:00,06-01-2020 12:39,Kanpur,374,SHOPLIFTING,25,M,Explosives,Other Crime,15,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40035,40036,28-07-2024 09:00,07-26-2024 03:00,26-07-2024 04:01,Ahmedabad,534,SHOPLIFTING,69,F,Blunt Object,Other Crime,6,No,NaN
40061,40062,29-07-2024 23:00,07-27-2024 05:00,27-07-2024 11:24,Indore,463,SHOPLIFTING,71,F,Firearm,Other Crime,15,No,NaN
40063,40064,29-07-2024 17:00,07-27-2024 07:00,28-07-2024 03:39,Delhi,468,SHOPLIFTING,74,M,Firearm,Other Crime,9,Yes,21-10-2024 17:00
40100,40101,31-07-2024 14:00,07-28-2024 20:00,29-07-2024 10:21,Bangalore,474,SHOPLIFTING,26,F,Blunt Object,Other Crime,5,Yes,02-10-2024 14:00
40106,40107,31-07-2024 12:00,07-29-2024 02:00,29-07-2024 19:29,Bangalore,453,SHOPLIFTING,79,F,Poison,Other Crime,4,No,NaN

In [15]:
df[
    (df['Crime Description']=="SHOPLIFTING") &
    (df['City']=="Mumbai")&
    (df['Victim Gender']=="M")
 ]

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
60,61,03-01-2020 22:00,01-03-2020 12:00,03-01-2020 15:04,Mumbai,196,SHOPLIFTING,16,M,Poison,Other Crime,10,No,NaN
285,286,15-01-2020 04:00,01-12-2020 21:00,13-01-2020 05:53,Mumbai,212,SHOPLIFTING,38,M,Other,Other Crime,11,Yes,25-03-2020 04:00
500,501,22-01-2020 23:00,01-21-2020 20:00,22-01-2020 08:30,Mumbai,408,SHOPLIFTING,18,M,NaN,Other Crime,19,Yes,14-04-2020 23:00
955,956,10-02-2020 13:00,02-09-2020 19:00,10-02-2020 00:38,Mumbai,172,SHOPLIFTING,69,M,Explosives,Other Crime,18,Yes,06-04-2020 13:00
2767,2768,26-04-2020 11:00,04-25-2020 07:00,25-04-2020 15:19,Mumbai,495,SHOPLIFTING,66,M,Poison,Other Crime,8,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36834,36835,15-03-2024 01:00,03-14-2024 18:00,14-03-2024 19:10,Mumbai,306,SHOPLIFTING,48,M,Explosives,Other Crime,12,Yes,21-04-2024 01:00
37070,37071,27-03-2024 01:00,03-24-2024 14:00,24-03-2024 20:57,Mumbai,264,SHOPLIFTING,27,M,Firearm,Other Crime,16,No,NaN
37559,37560,14-04-2024 09:00,04-13-2024 23:00,14-04-2024 22:22,Mumbai,452,SHOPLIFTING,76,M,Knife,Other Crime,6,Yes,20-06-2024 09:00
38110,38111,07-05-2024 03:00,05-06-2024 22:00,07-05-2024 08:33,Mumbai,563,SHOPLIFTING,24,M,Explosives,Other Crime,6,Yes,12-07-2024 03:00
39948,39949,22-07-2024 13:00,07-22-2024 12:00,22-07-2024 15:08,Mumbai,533,SHOPLIFTING,12,M,Other,Other Crime,15,No,NaN

In [17]:
df[
    (df['Crime Description']=="SHOPLIFTING") &
    (df['City']=="Mumbai")&
    (df['Victim Gender']=="M")&
    (df['Victim Age']>25)
 ]

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
285,286,15-01-2020 04:00,01-12-2020 21:00,13-01-2020 05:53,Mumbai,212,SHOPLIFTING,38,M,Other,Other Crime,11,Yes,25-03-2020 04:00
955,956,10-02-2020 13:00,02-09-2020 19:00,10-02-2020 00:38,Mumbai,172,SHOPLIFTING,69,M,Explosives,Other Crime,18,Yes,06-04-2020 13:00
2767,2768,26-04-2020 11:00,04-25-2020 07:00,25-04-2020 15:19,Mumbai,495,SHOPLIFTING,66,M,Poison,Other Crime,8,No,NaN
4043,4044,17-06-2020 13:00,06-17-2020 11:00,18-06-2020 08:57,Mumbai,324,SHOPLIFTING,36,M,Knife,Other Crime,2,Yes,09-09-2020 13:00
4448,4449,06-07-2020 13:00,07-04-2020 08:00,04-07-2020 13:57,Mumbai,420,SHOPLIFTING,27,M,Blunt Object,Other Crime,14,Yes,14-07-2020 13:00
4547,4548,09-07-2020 22:00,07-08-2020 11:00,08-07-2020 14:40,Mumbai,294,SHOPLIFTING,74,M,Poison,Other Crime,10,Yes,16-08-2020 22:00
6195,6196,17-09-2020 12:00,09-15-2020 03:00,15-09-2020 18:03,Mumbai,448,SHOPLIFTING,64,M,Poison,Other Crime,6,Yes,24-09-2020 12:00
7519,7520,11-11-2020 01:00,11-09-2020 07:00,09-11-2020 18:44,Mumbai,566,SHOPLIFTING,70,M,Poison,Other Crime,19,No,NaN
8050,8051,02-12-2020 23:00,12-01-2020 10:00,01-12-2020 20:08,Mumbai,313,SHOPLIFTING,69,M,Knife,Other Crime,9,Yes,23-12-2020 23:00
8639,8640,28-12-2020 19:00,12-25-2020 23:00,26-12-2020 01:29,Mumbai,463,SHOPLIFTING,75,M,Explosives,Other Crime,4,Yes,20-03-2021 19:00
10025,10026,23-02-2021 06:00,02-21-2021 17:00,22-02-2021 10:36,Mumbai,505,SHOPLIFTING,36,M,Knife,Other Crime,4,Yes,20-05-2021 06:00
10394,10395,10-03-2021 16:00,03-09-2021 02:00,09-03-2021 12:34,Mumbai,394,SHOPLIFTING,57,M,Poison,Other Crime,1,Yes,17-03-2021 16:00
10655,10656,22-03-2021 20:00,03-19-2021 23:00,20-03-2021 04:47,Mumbai,243,SHOPLIFTING,35,M,Poison,Other Crime,18,No,NaN
10781,10782,26-03-2021 05:00,03-25-2021 05:00,25-03-2021 07:15,Mumbai,592,SHOPLIFTING,60,M,Poison,Other Crime,14,No,NaN
13478,13479,17-07-2021 23:00,07-15-2021 14:00,15-07-2021 23:39,Mumbai,386,SHOPLIFTING,37,M,Knife,Other Crime,12,Yes,21-08-2021 23:00
13749,13750,27-07-2021 08:00,07-26-2021 21:00,27-07-2021 14:04,Mumbai,102,SHOPLIFTING,32,M,Explosives,Other Crime,14,No,NaN
13909,13910,04-08-2021 19:00,08-02-2021 13:00,03-08-2021 10:02,Mumbai,479,SHOPLIFTING,39,M,Blunt Object,Other Crime,7,No,NaN
14475,14476,27-08-2021 05:00,08-26-2021 03:00,26-08-2021 15:41,Mumbai,420,SHOPLIFTING,74,M,Explosives,Other Crime,12,No,NaN
14969,14970,17-09-2021 01:00,09-15-2021 17:00,16-09-2021 07:03,Mumbai,204,SHOPLIFTING,74,M,Knife,Other Crime,11,Yes,28-10-2021 01:00
15715,15716,17-10-2021 07:00,10-16-2021 19:00,17-10-2021 14:52,Mumbai,325,SHOPLIFTING,78,M,Poison,Other Crime,6,Yes,29-10-2021 07:00
15898,15899,26-10-2021 09:00,10-24-2021 10:00,24-10-2021 22:31,Mumbai,375,SHOPLIFTING,30,M,Explosives,Other Crime,10,No,NaN
16015,16016,31-10-2021 11:00,10-29-2021 07:00,29-10-2021 18:19,Mumbai,280,SHOPLIFTING,77,M,Knife,Other Crime,3,Yes,28-12-2021 11:00
16402,16403,15-11-2021 08:00,11-14-2021 10:00,14-11-2021 10:23,Mumbai,576,SHOPLIFTING,39,M,Poison,Other Crime,8,Yes,07-01-2022 08:00
16723,16724,28-11-2021 15:00,11-27-2021 19:00,28-11-2021 01:53,Mumbai,182,SHOPLIFTING,54,M,Firearm,Other Crime,4,Yes,10-02-2022 15:00
17562,17563,03-01-2022 18:00,01-01-2022 18:00,01-01-2022 20:19,Mumbai,153,SHOPLIFTING,69,M,Blunt Object,Other Crime,8,No,NaN
19184,19185,13-03-2022 03:00,03-10-2022 08:00,11-03-2022 01:27,Mumbai,355,SHOPLIFTING,61,M,Blunt Object,Other Crime,17,No,NaN
19667,19668,30-03-2022 15:00,03-30-2022 11:00,31-03-2022 02:37,Mumbai,418,SHOPLIFTING,27,M,Blunt Object,Other Crime,8,No,NaN
19682,19683,31-03-2022 08:00,03-31-2022 02:00,31-03-2022 23:40,Mumbai,523,SHOPLIFTING,63,M,Explosives,Other Crime,8,Yes,20-04-2022 08:00
19695,19696,02-04-2022 12:00,03-31-2022 15:00,31-03-2022 23:53,Mumbai,242,SHOPLIFTING,75,M,Explosives,Other Crime,10,No,NaN
20062,20063,16-04-2022 07:00,04-15-2022 22:00,16-04-2022 05:49,Mumbai,452,SHOPLIFTING,47,M,Explosives,Other Crime,5,Yes,04-07-2022 07:00
20774,20775,16-05-2022 02:00,05-15-2022 14:00,15-05-2022 14:11,Mumbai,436,SHOPLIFTING,74,M,NaN,Other Crime,1,Yes,14-07-2022 02:00
22037,22038,07-07-2022 16:00,07-07-2022 05:00,07-07-2022 11:17,Mumbai,147,SHOPLIFTING,60,M,Knife,Other Crime,6,No,NaN
22120,22121,13-07-2022 15:00,07-10-2022 16:00,11-07-2022 11:38,Mumbai,262,SHOPLIFTING,31,M,Explosives,Other Crime,15,No,NaN
22328,22329,21-07-2022 13:00,07-19-2022 08:00,20-07-2022 04:39,Mumbai,305,SHOPLIFTING,73,M,Other,Other Crime,19,Yes,03-08-2022 13:00
23459,23460,05-09-2022 06:00,09-04-2022 11:00,05-09-2022 01:05,Mumbai,396,SHOPLIFTING,56,M,Blunt Object,Other Crime,5,No,NaN
25485,25486,28-11-2022 08:00,11-27-2022 21:00,28-11-2022 15:27,Mumbai,149,SHOPLIFTING,78,M,Blunt Object,Other Crime,13,No,NaN
26383,26384,05-01-2023 08:00,01-04-2023 07:00,04-01-2023 16:56,Mumbai,527,SHOPLIFTING,52,M,NaN,Other Crime,8,Yes,16-02-2023 08:00
28372,28373,30-03-2023 16:00,03-28-2023 04:00,29-03-2023 01:09,Mumbai,259,SHOPLIFTING,78,M,NaN,Other Crime,4,No,NaN
28848,28849,17-04-2023 15:00,04-17-2023 00:00,17-04-2023 01:47,Mumbai,542,SHOPLIFTING,61,M,Explosives,Other Crime,5,Yes,13-07-2023 15:00
29886,29887,01-06-2023 06:00,05-30-2023 06:00,30-05-2023 14:49,Mumbai,358,SHOPLIFTING,30,M,Blunt Object,Other Crime,9,Yes,06-08-2023 06:00
30088,30089,08-06-2023 09:00,06-07-2023 16:00,08-06-2023 08:52,Mumbai,382,SHOPLIFTING,37,M,NaN,Other Crime,6,No,NaN
30239,30240,14-06-2023 00:00,06-13-2023 23:00,14-06-2023 03:01,Mumbai,503,SHOPLIFTING,40,M,Blunt Object,Other Crime,18,No,NaN
34228,34229,27-11-2023 07:00,11-27-2023 04:00,27-11-2023 17:49,Mumbai,538,SHOPLIFTING,49,M,Poison,Other Crime,13,No,NaN
34470,34471,08-12-2023 18:00,12-07-2023 06:00,07-12-2023 18:36,Mumbai,231,SHOPLIFTING,47,M,Explosives,Other Crime,10,No,NaN
34946,34947,28-12-2023 01:00,12-27-2023 02:00,27-12-2023 14:12,Mumbai,325,SHOPLIFTING,44,M,Firearm,Other Crime,5,No,NaN
35147,35148,06-01-2024 17:00,01-04-2024 11:00,04-01-2024 19:18,Mumbai,347,SHOPLIFTING,59,M,Explosives,Other Crime,16,Yes,01-03-2024 17:00
35394,35395,16-01-2024 13:00,01-14-2024 18:00,15-01-2024 11:31,Mumbai,594,SHOPLIFTING,28,M,Explosives,Other Crime,6,No,NaN
36028,36029,12-02-2024 01:00,02-10-2024 04:00,10-02-2024 17:51,Mumbai,485,SHOPLIFTING,72,M,Blunt Object,Other Crime,11,No,NaN
36834,36835,15-03-2024 01:00,03-14-2024 18:00,14-03-2024 19:10,Mumbai,306,SHOPLIFTING,48,M,Explosives,Other Crime,12,Yes,21-04-2024 01:00
37070,37071,27-03-2024 01:00,03-24-2024 14:00,24-03-2024 20:57,Mumbai,264,SHOPLIFTING,27,M,Firearm,Other Crime,16,No,NaN
37559,37560,14-04-2024 09:00,04-13-2024 23:00,14-04-2024 22:22,Mumbai,452,SHOPLIFTING,76,M,Knife,Other Crime,6,Yes,20-06-2024 09:00

In [18]:
df[
    df['City'].str.startswith("A",na=False)
 ]

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
0,1,02-01-2020 00:00,01-01-2020 00:00,01-01-2020 01:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
57,58,03-01-2020 18:00,01-03-2020 09:00,03-01-2020 09:43,Ahmedabad,110,ASSAULT,70,F,NaN,Violent Crime,15,No,NaN
74,75,05-01-2020 02:00,01-04-2020 02:00,05-01-2020 01:45,Ahmedabad,404,CYBERCRIME,70,F,Knife,Other Crime,18,No,NaN
100,101,06-01-2020 23:00,01-05-2020 04:00,05-01-2020 14:02,Ahmedabad,515,PUBLIC INTOXICATION,50,F,Knife,Other Crime,1,Yes,14-01-2020 23:00
120,121,07-01-2020 14:00,01-06-2020 00:00,06-01-2020 12:16,Ahmedabad,277,VEHICLE - STOLEN,78,F,Firearm,Violent Crime,10,Yes,22-01-2020 14:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40060,40061,27-07-2024 08:00,07-27-2024 04:00,27-07-2024 22:50,Ahmedabad,321,ILLEGAL POSSESSION,75,M,Knife,Other Crime,15,Yes,08-10-2024 08:00
40088,40089,30-07-2024 00:00,07-28-2024 08:00,28-07-2024 22:56,Agra,477,ROBBERY,40,F,Explosives,Violent Crime,9,No,NaN
40091,40092,28-07-2024 21:00,07-28-2024 11:00,28-07-2024 15:58,Agra,164,COUNTERFEITING,41,F,Poison,Other Crime,12,Yes,08-08-2024 21:00
40094,40095,29-07-2024 14:00,07-28-2024 14:00,29-07-2024 09:46,Agra,144,KIDNAPPING,19,F,Other,Other Crime,12,Yes,20-10-2024 14:00
40105,40106,30-07-2024 00:00,07-29-2024 01:00,29-07-2024 22:56,Agra,102,ILLEGAL POSSESSION,47,F,Firearm,Other Crime,12,Yes,20-10-2024 00:00

In [19]:
df[
    df['City'].str.startswith("N",na=False)
 ]

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
50,51,03-01-2020 05:00,01-03-2020 02:00,03-01-2020 17:10,Nagpur,573,BURGLARY,54,F,Other,Other Crime,12,Yes,13-04-2020 05:00
71,72,05-01-2020 18:00,01-03-2020 23:00,04-01-2020 11:34,Nagpur,244,ARSON,53,F,Knife,Fire Accident,1,Yes,23-03-2020 18:00
96,97,06-01-2020 02:00,01-05-2020 00:00,05-01-2020 15:36,Nagpur,523,IDENTITY THEFT,26,F,Explosives,Violent Crime,5,Yes,12-02-2020 02:00
187,188,09-01-2020 18:00,01-08-2020 19:00,09-01-2020 18:53,Nagpur,236,IDENTITY THEFT,66,F,NaN,Violent Crime,14,Yes,15-03-2020 18:00
199,200,11-01-2020 13:00,01-09-2020 07:00,10-01-2020 02:06,Nashik,471,HOMICIDE,56,F,Blunt Object,Other Crime,4,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39902,39903,21-07-2024 02:00,07-20-2024 14:00,20-07-2024 16:08,Nashik,145,CYBERCRIME,18,M,Blunt Object,Other Crime,14,No,NaN
39912,39913,23-07-2024 22:00,07-21-2024 00:00,21-07-2024 11:52,Nashik,226,BURGLARY,31,F,Explosives,Other Crime,7,No,NaN
39920,39921,23-07-2024 10:00,07-21-2024 08:00,21-07-2024 14:22,Nashik,570,ASSAULT,68,F,Firearm,Violent Crime,2,Yes,19-09-2024 10:00
40077,40078,28-07-2024 17:00,07-27-2024 21:00,28-07-2024 00:04,Nagpur,256,ROBBERY,56,M,Knife,Violent Crime,10,No,NaN
40089,40090,30-07-2024 14:00,07-28-2024 09:00,28-07-2024 23:47,Nagpur,521,BURGLARY,69,F,Explosives,Other Crime,7,Yes,12-12-2024 14:00

In [21]:
df[
    df['City'].str.endswith("a",na=False)
 ]

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
2,3,02-01-2020 05:00,01-01-2020 02:00,01-01-2020 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
15,16,02-01-2020 07:00,01-01-2020 15:00,01-01-2020 18:54,Kolkata,357,COUNTERFEITING,51,F,Explosives,Other Crime,16,Yes,30-03-2020 07:00
33,34,05-01-2020 07:00,01-02-2020 09:00,03-01-2020 02:40,Patna,575,VEHICLE - STOLEN,24,F,Explosives,Violent Crime,6,No,NaN
44,45,05-01-2020 19:00,01-02-2020 20:00,03-01-2020 06:22,Kolkata,387,ARSON,44,F,Blunt Object,Fire Accident,10,Yes,12-01-2020 19:00
45,46,04-01-2020 19:00,01-02-2020 21:00,03-01-2020 09:02,Patna,297,DRUG OFFENSE,67,M,Knife,Other Crime,8,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40141,40142,01-08-2024 04:00,07-30-2024 13:00,31-07-2024 03:26,Patna,365,IDENTITY THEFT,60,F,Poison,Violent Crime,17,Yes,05-09-2024 04:00
40147,40148,02-08-2024 18:00,07-30-2024 19:00,30-07-2024 21:30,Ludhiana,345,ILLEGAL POSSESSION,17,F,Poison,Other Crime,14,No,NaN
40153,40154,31-07-2024 17:00,07-31-2024 01:00,31-07-2024 21:42,Kolkata,567,PUBLIC INTOXICATION,71,F,Blunt Object,Other Crime,14,Yes,22-08-2024 17:00
40155,40156,01-08-2024 16:00,07-31-2024 03:00,31-07-2024 05:05,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,NaN
40158,40159,01-08-2024 19:00,07-31-2024 06:00,31-07-2024 11:05,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,NaN

In [24]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("gregorut/videogamesales")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/gregorut/videogamesales/2.archive...

100%|██████████| 381k/381k [00:00<00:00, 551kB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/gregorut/videogamesales/versions/2

In [25]:
path="/root/.cache/kagglehub/datasets/gregorut/videogamesales/versions/2"
df=pd.read_csv(path+"/vgsales.csv")

In [26]:
df.shape

(16598, 11)

In [27]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [29]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [33]:
df.sort_values(
    "Global_Sales",ascending=False).head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [34]:
df.sort_values("Global_Sales",ascending=True).head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16584,16587,Bust-A-Move 3000,GC,2003.0,Puzzle,Ubisoft,0.01,0.00,0.00,0.0,0.01
16583,16586,Carmageddon 64,N64,1999.0,Action,Virgin Interactive,0.01,0.00,0.00,0.0,0.01
16582,16585,Planet Monsters,GBA,2001.0,Action,Titus,0.01,0.00,0.00,0.0,0.01
16581,16584,Fit & Fun,Wii,2011.0,Sports,Unknown,0.00,0.01,0.00,0.0,0.01
16580,16583,Real Rode,PS2,2008.0,Adventure,Kadokawa Shoten,0.00,0.00,0.01,0.0,0.01

In [35]:
df['Genre'].value_counts()

Genre
Action          3316
Sports          2346
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         886
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
Name: count, dtype: int64

In [36]:
df['Platform'].value_counts()

Platform
DS      2163
PS2     2161
PS3     1329
Wii     1325
X360    1265
PSP     1213
PS      1196
PC       960
XB       824
GBA      822
GC       556
3DS      509
PSV      413
PS4      336
N64      319
SNES     239
XOne     213
SAT      173
WiiU     143
2600     133
NES       98
GB        98
DC        52
GEN       27
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

In [38]:
df[
    df['Genre']=="Action"
 ]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
23,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
24,25,Grand Theft Auto: Vice City,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15
38,39,Grand Theft Auto III,PS2,2001.0,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10
...,...,...,...,...,...,...,...,...,...,...,...
16564,16567,Original Frisbee Disc Sports: Ultimate & Golf,DS,2007.0,Action,"Destination Software, Inc",0.01,0.00,0.00,0.00,0.01
16567,16570,Fujiko F. Fujio Characters: Great Assembly! Sl...,3DS,2014.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01
16582,16585,Planet Monsters,GBA,2001.0,Action,Titus,0.01,0.00,0.00,0.00,0.01
16583,16586,Carmageddon 64,N64,1999.0,Action,Virgin Interactive,0.01,0.00,0.00,0.00,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.00,0.01

In [40]:
df[(df['Genre']=="Sports")&(df['Year']>2015)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
221,222,FIFA 17,PS4,2016.0,Sports,Electronic Arts,0.28,3.75,0.06,0.69,4.77
1224,1226,FIFA 17,XOne,2016.0,Sports,Electronic Arts,0.17,1.26,0.00,0.10,1.53
1628,1630,Madden NFL 17,PS4,2016.0,Sports,Electronic Arts,0.92,0.08,0.00,0.23,1.23
1701,1703,NBA 2K17,PS4,2016.0,Sports,Take-Two Interactive,0.83,0.14,0.00,0.22,1.19
2342,2344,EA Sports UFC 2,PS4,2016.0,Sports,Electronic Arts,0.28,0.47,0.00,0.14,0.89
2505,2507,Madden NFL 17,XOne,2016.0,Sports,Electronic Arts,0.72,0.02,0.00,0.09,0.82
3145,3147,NBA 2K17,XOne,2016.0,Sports,Take-Two Interactive,0.54,0.04,0.00,0.07,0.64
4820,4822,EA Sports UFC 2,XOne,2016.0,Sports,Electronic Arts,0.23,0.14,0.00,0.04,0.40
5056,5058,FIFA 17,PS3,2016.0,Sports,Electronic Arts,0.02,0.29,0.01,0.05,0.38
6136,6138,Pro Evolution Soccer 2017,PS4,2016.0,Sports,Konami Digital Entertainment,0.01,0.16,0.09,0.03,0.28
6205,6207,UEFA Euro 2016,PS4,2016.0,Sports,Konami Digital Entertainment,0.00,0.21,0.03,0.03,0.28
7072,7074,Rocket League,PS4,2016.0,Sports,505 Games,0.02,0.14,0.00,0.07,0.23
7575,7577,NHL 17,PS4,2016.0,Sports,Electronic Arts,0.13,0.04,0.00,0.04,0.20
8190,8192,FIFA 17,X360,2016.0,Sports,Electronic Arts,0.03,0.13,0.00,0.01,0.18
8221,8223,Jikkyou Powerful Pro Baseball 2016,PSV,2016.0,Sports,Konami Digital Entertainment,0.00,0.00,0.17,0.00,0.17
8400,8402,Jikkyou Powerful Pro Baseball 2016,PS4,2016.0,Sports,Konami Digital Entertainment,0.00,0.00,0.17,0.00,0.17
8751,8753,NHL 17,XOne,2016.0,Sports,Electronic Arts,0.13,0.01,0.00,0.02,0.15
9711,9713,Rocket League,XOne,2016.0,Sports,505 Games,0.03,0.09,0.00,0.01,0.12
10040,10042,UEFA Euro 2016,PS3,2016.0,Sports,Konami Digital Entertainment,0.00,0.08,0.02,0.01,0.11
10156,10158,Jikkyou Powerful Pro Baseball 2016,PS3,2016.0,Sports,Konami Digital Entertainment,0.00,0.00,0.11,0.00,0.11
11564,11566,Madden NFL 17,X360,2016.0,Sports,Electronic Arts,0.06,0.01,0.00,0.01,0.08
11704,11706,Madden NFL 17,PS3,2016.0,Sports,Electronic Arts,0.05,0.01,0.00,0.01,0.08
12412,12414,Pro Evolution Soccer 2017,PS3,2016.0,Sports,Konami Digital Entertainment,0.00,0.01,0.04,0.00,0.06
12869,12871,NBA 2K17,X360,2016.0,Sports,Take-Two Interactive,0.04,0.00,0.00,0.01,0.05
12938,12940,FIFA 17,PC,2016.0,Sports,Electronic Arts,0.00,0.05,0.00,0.00,0.05
12987,12989,Dead or Alive Xtreme 3: Fortune,PS4,2016.0,Sports,Tecmo Koei,0.00,0.00,0.05,0.00,0.05
13170,13172,Pro Cycling Manager 2016,PS4,2016.0,Sports,Focus Home Interactive,0.00,0.04,0.00,0.01,0.05
13232,13234,NBA 2K17,PS3,2016.0,Sports,Take-Two Interactive,0.03,0.01,0.00,0.01,0.05
13492,13494,Rugby Challenge 3,PS3,2016.0,Sports,Alternative Software,0.00,0.04,0.00,0.01,0.04
13529,13531,R.B.I. Baseball 2016,XOne,2016.0,Sports,MLB.com,0.04,0.00,0.00,0.00,0.04
13881,13883,Rugby Challenge 3,PS4,2016.0,Sports,Alternative Software,0.00,0.03,0.00,0.01,0.04
14201,14204,Dead or Alive Xtreme 3: Venus,PSV,2016.0,Sports,Tecmo Koei,0.00,0.00,0.03,0.00,0.03
14555,14558,Pro Cycling Manager 2016,PC,2016.0,Sports,Focus Home Interactive,0.00,0.03,0.00,0.00,0.03
14738,14741,Pro Evolution Soccer 2017,XOne,2016.0,Sports,Konami Digital Entertainment,0.00,0.02,0.00,0.00,0.03
14983,14986,Rugby Challenge 3,X360,2016.0,Sports,Alternative Software,0.00,0.02,0.00,0.00,0.02
15150,15153,Rocket League,PC,2016.0,Sports,505 Games,0.01,0.01,0.00,0.00,0.02
15464,15467,Dino Dini's Kick Off Revival,PS4,2016.0,Sports,Avanquest,0.00,0.02,0.00,0.00,0.02
16576,16579,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.00,0.00,0.01

In [42]:
df[(df['Platform']=='PS4')&(df['Genre']=='Action')]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
44,45,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
236,237,The Last of Us,PS4,2014.0,Action,Sony Computer Entertainment,1.78,1.87,0.07,0.82,4.55
243,244,Uncharted: The Nathan Drake Collection,PS4,2015.0,Action,Sony Computer Entertainment,1.96,1.69,0.08,0.74,4.47
280,281,Watch Dogs,PS4,2014.0,Action,Ubisoft,1.40,1.86,0.11,0.77,4.14
304,305,Assassin's Creed: Unity,PS4,2014.0,Action,Ubisoft,1.18,1.96,0.08,0.70,3.92
...,...,...,...,...,...,...,...,...,...,...,...
16136,16139,Dragon's Dogma Online: Season 2,PS4,2016.0,Action,Capcom,0.00,0.00,0.01,0.00,0.01
16175,16178,Republique,PS4,2016.0,Action,Nippon Ichi Software,0.00,0.01,0.01,0.00,0.01
16220,16223,Dynasty Warriors: Eiketsuden,PS4,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
16260,16263,Paragon,PS4,2016.0,Action,Epic Games,0.01,0.00,0.00,0.00,0.01
16550,16553,God Eater Off Shot: Tachibana Sakuya-hen Twin ...,PS4,2016.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01

In [44]:
df[(df['Platform']=='PS4')&(df['Genre']=='Action')&(df['Year']>2015)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
770,772,Far Cry: Primal,PS4,2016.0,Action,Ubisoft,0.59,1.16,0.06,0.33,2.13
1156,1158,No Man's Sky,PS4,2016.0,Action,Hello Games,0.58,0.74,0.02,0.26,1.60
2457,2459,MLB 16: The Show,PS4,2016.0,Action,Sony Computer Entertainment,0.68,0.00,0.00,0.16,0.84
3149,3151,LEGO Marvel's Avengers,PS4,2016.0,Action,Warner Bros. Interactive Entertainment,0.25,0.29,0.00,0.10,0.64
3746,3748,Lego Star Wars: The Force Awakens,PS4,2016.0,Action,Warner Bros. Interactive Entertainment,0.14,0.32,0.00,0.08,0.54
5172,5174,Resident Evil Zero,PS4,2016.0,Action,Capcom,0.09,0.17,0.05,0.05,0.36
5621,5623,TrackMania Turbo,PS4,2016.0,Action,Ubisoft,0.03,0.24,0.00,0.05,0.32
6203,6205,Dragon Quest Heroes II: Twin Kings and the Pro...,PS4,2016.0,Action,Square Enix,0.00,0.00,0.28,0.00,0.28
7497,7499,Attack on Titan (KOEI),PS4,2016.0,Action,Tecmo Koei,0.02,0.06,0.11,0.02,0.20
7892,7894,The Heavy Rain and Beyond: Two Souls Collection,PS4,2016.0,Action,Sony Computer Entertainment,0.00,0.16,0.00,0.03,0.19
9878,9880,7 Days to Die,PS4,2016.0,Action,Telltale Games,0.03,0.07,0.00,0.02,0.12
9993,9995,Dead Island Definitive Collection,PS4,2016.0,Action,Deep Silver,0.02,0.07,0.01,0.02,0.12
10844,10846,Gundam Breaker 3,PS4,2016.0,Action,Namco Bandai Games,0.00,0.00,0.09,0.00,0.09
11424,11426,Toukiden 2,PS4,2016.0,Action,Tecmo Koei,0.00,0.00,0.08,0.00,0.08
11581,11583,Assassin's Creed Chronicles,PS4,2016.0,Action,Ubisoft,0.01,0.05,0.01,0.01,0.08
11841,11843,Teenage Mutant Ninja Turtles: Mutants in Manha...,PS4,2016.0,Action,Activision,0.04,0.02,0.00,0.01,0.07
12388,12390,Song of the Deep,PS4,2016.0,Action,Insomniac Games,0.05,0.00,0.00,0.01,0.06
12835,12837,Kamen Rider: Battride War Genesis,PS4,2016.0,Action,Namco Bandai Games,0.00,0.00,0.05,0.00,0.05
12925,12927,ZombiU,PS4,2016.0,Action,Ubisoft,0.00,0.04,0.01,0.01,0.05
13647,13649,Hitman (2016),PS4,2016.0,Action,Square Enix,0.00,0.04,0.00,0.01,0.04
14427,14430,Summon Night 6: Lost Borders,PS4,2016.0,Action,Namco Bandai Games,0.00,0.00,0.03,0.00,0.03
14680,14683,Ghostbusters (2016),PS4,2016.0,Action,Activision,0.02,0.00,0.00,0.01,0.03
14811,14814,Sengoku Basara: Sanada Yukimura-Den,PS4,2016.0,Action,Capcom,0.00,0.00,0.03,0.00,0.03
15082,15085,Prison Architect,PS4,2016.0,Action,Introversion Software,0.01,0.01,0.00,0.00,0.02
15166,15169,Aegis of Earth: Protonovus Assault,PS4,2016.0,Action,PQube,0.02,0.00,0.00,0.00,0.02
15338,15341,Dead Rising,PS4,2016.0,Action,Capcom,0.01,0.00,0.00,0.00,0.02
15394,15397,Anima - Gate of Memories,PS4,2016.0,Action,Avanquest,0.00,0.02,0.00,0.00,0.02
15403,15406,Resident Evil: Umbrella Corps,PS4,2016.0,Action,Capcom,0.00,0.00,0.02,0.00,0.02
15714,15717,This War of Mine,PS4,2016.0,Action,Deep Silver,0.00,0.01,0.00,0.00,0.02
15940,15943,Worms: WMD,PS4,2016.0,Action,Sold Out,0.01,0.01,0.00,0.00,0.02
16019,16022,God Eater Off Shot: Soma Shikkuzaru-hen Twin P...,PS4,2016.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01
16095,16098,Resident Evil 5 HD,PS4,2016.0,Action,Capcom,0.01,0.00,0.00,0.00,0.01
16136,16139,Dragon's Dogma Online: Season 2,PS4,2016.0,Action,Capcom,0.00,0.00,0.01,0.00,0.01
16175,16178,Republique,PS4,2016.0,Action,Nippon Ichi Software,0.00,0.01,0.01,0.00,0.01
16220,16223,Dynasty Warriors: Eiketsuden,PS4,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
16260,16263,Paragon,PS4,2016.0,Action,Epic Games,0.01,0.00,0.00,0.00,0.01
16550,16553,God Eater Off Shot: Tachibana Sakuya-hen Twin ...,PS4,2016.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01

In [45]:
df["Publisher"].value_counts().head()

Publisher
Electronic Arts                 1351
Activision                       975
Namco Bandai Games               932
Ubisoft                          921
Konami Digital Entertainment     832
Name: count, dtype: int64

In [46]:
df.groupby("Genre")["Global_Sales"].sum()

Genre
Action          1751.18
Adventure        239.04
Fighting         448.91
Misc             809.96
Platform         831.37
Puzzle           244.95
Racing           732.04
Role-Playing     927.37
Shooter         1037.37
Simulation       392.20
Sports          1330.93
Strategy         175.12
Name: Global_Sales, dtype: float64

In [47]:
genre_sales=df.groupby("Genre")["Global_Sales"].sum()

In [49]:
print(genre_sales.sort_values(ascending=True))

Genre
Strategy         175.12
Adventure        239.04
Puzzle           244.95
Simulation       392.20
Fighting         448.91
Racing           732.04
Misc             809.96
Platform         831.37
Role-Playing     927.37
Shooter         1037.37
Sports          1330.93
Action          1751.18
Name: Global_Sales, dtype: float64

In [50]:
platform_sales=df.groupby("Platform")["Global_Sales"].sum()

print(platform_sales.sort_values(ascending=False))

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Wii      926.71
DS       822.49
PS       730.66
GBA      318.50
PSP      296.28
PS4      278.10
PC       258.82
XB       258.26
GB       255.45
NES      251.07
3DS      247.46
N64      218.88
SNES     200.05
GC       199.36
XOne     141.06
2600      97.08
WiiU      81.86
PSV       61.93
SAT       33.59
GEN       28.36
DC        15.97
SCD        1.87
NG         1.44
WS         1.42
TG16       0.16
3DO        0.10
GG         0.04
PCFX       0.03
Name: Global_Sales, dtype: float64

In [51]:
publisher_sales=df.groupby("Publisher")["Global_Sales"].sum()

print(publisher_sales.sort_values(ascending=False).head())

Publisher
Nintendo                       1786.56
Electronic Arts                1110.32
Activision                      727.46
Sony Computer Entertainment     607.50
Ubisoft                         474.72
Name: Global_Sales, dtype: float64

In [52]:
year_sales=df.groupby("Year")["Global_Sales"].sum()

year_sales

Year
1980.0     11.38
1981.0     35.77
1982.0     28.86
1983.0     16.79
1984.0     50.36
1985.0     53.94
1986.0     37.07
1987.0     21.74
1988.0     47.22
1989.0     73.45
1990.0     49.39
1991.0     32.23
1992.0     76.16
1993.0     45.98
1994.0     79.17
1995.0     88.11
1996.0    199.15
1997.0    200.98
1998.0    256.47
1999.0    251.27
2000.0    201.56
2001.0    331.47
2002.0    395.52
2003.0    357.85
2004.0    419.31
2005.0    459.94
2006.0    521.04
2007.0    611.13
2008.0    678.90
2009.0    667.30
2010.0    600.45
2011.0    515.99
2012.0    363.54
2013.0    368.11
2014.0    337.05
2015.0    264.44
2016.0     70.93
2017.0      0.05
2020.0      0.29
Name: Global_Sales, dtype: float64

In [54]:
year_sales.sort_values(ascending=True)
year_sales

Year
1980.0     11.38
1981.0     35.77
1982.0     28.86
1983.0     16.79
1984.0     50.36
1985.0     53.94
1986.0     37.07
1987.0     21.74
1988.0     47.22
1989.0     73.45
1990.0     49.39
1991.0     32.23
1992.0     76.16
1993.0     45.98
1994.0     79.17
1995.0     88.11
1996.0    199.15
1997.0    200.98
1998.0    256.47
1999.0    251.27
2000.0    201.56
2001.0    331.47
2002.0    395.52
2003.0    357.85
2004.0    419.31
2005.0    459.94
2006.0    521.04
2007.0    611.13
2008.0    678.90
2009.0    667.30
2010.0    600.45
2011.0    515.99
2012.0    363.54
2013.0    368.11
2014.0    337.05
2015.0    264.44
2016.0     70.93
2017.0      0.05
2020.0      0.29
Name: Global_Sales, dtype: float64

In [57]:
df[["NA_Sales",
    "EU_Sales",
    "JP_Sales",
    "Other_Sales"]].sum()

NA_Sales       4392.95
EU_Sales       2434.13
JP_Sales       1291.02
Other_Sales     797.75
dtype: float64

In [58]:
df[df["Name"].str.contains("Grand Theft Auto",na=False)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
23,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
24,25,Grand Theft Auto: Vice City,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15
38,39,Grand Theft Auto III,PS2,2001.0,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10
44,45,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
51,52,Grand Theft Auto IV,X360,2008.0,Action,Take-Two Interactive,6.76,3.10,0.14,1.03,11.02
56,57,Grand Theft Auto IV,PS3,2008.0,Action,Take-Two Interactive,4.76,3.76,0.44,1.62,10.57
90,91,Grand Theft Auto: Liberty City Stories,PSP,2005.0,Action,Take-Two Interactive,2.90,2.83,0.24,1.75,7.72
197,198,Grand Theft Auto V,XOne,2014.0,Action,Take-Two Interactive,2.66,2.01,0.00,0.41,5.08
198,199,Grand Theft Auto: Vice City Stories,PSP,2006.0,Action,Take-Two Interactive,1.70,2.02,0.16,1.21,5.08
360,361,Grand Theft Auto: Liberty City Stories,PS2,2006.0,Action,Take-Two Interactive,1.56,1.40,0.07,0.50,3.54
388,389,Grand Theft Auto 2,PS,1998.0,Action,Take-Two Interactive,1.13,2.07,0.00,0.22,3.42
617,618,Rockstar Games Double Pack: Grand Theft Auto I...,XB,2003.0,Action,Take-Two Interactive,1.84,0.56,0.00,0.09,2.49
684,686,Grand Theft Auto,PS,1997.0,Action,Take-Two Interactive,0.79,1.35,0.04,0.14,2.32
873,875,Grand Theft Auto: San Andreas,XB,2005.0,Action,Take-Two Interactive,1.26,0.61,0.00,0.09,1.95
1032,1034,Rockstar Games Double Pack: Grand Theft Auto I...,PS2,2003.0,Action,Take-Two Interactive,0.85,0.66,0.00,0.22,1.72
1441,1443,Grand Theft Auto: Chinatown Wars,DS,2009.0,Action,Take-Two Interactive,0.59,0.57,0.05,0.14,1.35
1896,1898,Grand Theft Auto V,PC,2015.0,Action,Take-Two Interactive,0.36,0.64,0.00,0.08,1.08
1902,1904,Grand Theft Auto: Chinatown Wars,PSP,2009.0,Action,Take-Two Interactive,0.28,0.50,0.03,0.28,1.08
2120,2122,Grand Theft Auto: San Andreas,PC,2005.0,Action,Take-Two Interactive,0.00,0.92,0.00,0.05,0.98
2138,2140,Grand Theft Auto: Vice City Stories,PS2,2007.0,Action,Take-Two Interactive,0.78,0.03,0.03,0.13,0.97
2357,2359,Grand Theft Auto IV,PC,2008.0,Action,Take-Two Interactive,0.01,0.79,0.00,0.08,0.88
6905,6907,Grand Theft Auto,GBA,2004.0,Action,Take-Two Interactive,0.17,0.06,0.00,0.00,0.24
9827,9829,Grand Theft Auto: San Andreas,X360,2008.0,Action,Take-Two Interactive,0.08,0.03,0.00,0.01,0.12
10379,10381,"Grand Theft Auto: Mission Pack #1, London 1969",PS,1998.0,Adventure,Take-Two Interactive,0.06,0.04,0.00,0.01,0.11
13732,13734,Grand Theft Auto: Vice City,PC,2003.0,Action,Take-Two Interactive,0.00,0.03,0.00,0.01,0.04
16093,16096,Grand Theft Auto III,PC,2002.0,Action,Take-Two Interactive,0.00,0.01,0.00,0.00,0.01

In [59]:
df[df["Name"].str.contains("Far Cry",na=False)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
295,296,Far Cry 4,PS4,2014.0,Shooter,Ubisoft,1.12,2.12,0.10,0.69,4.03
382,383,Far Cry 3,PS3,2012.0,Shooter,Ubisoft,0.88,1.75,0.10,0.72,3.45
459,460,Far Cry 3,X360,2012.0,Shooter,Ubisoft,1.38,1.35,0.02,0.28,3.04
770,772,Far Cry: Primal,PS4,2016.0,Action,Ubisoft,0.59,1.16,0.06,0.33,2.13
1147,1149,Far Cry 4,XOne,2014.0,Shooter,Ubisoft,0.79,0.68,0.01,0.13,1.61
1151,1153,Far Cry 2,X360,2008.0,Action,Ubisoft,0.71,0.69,0.02,0.18,1.60
1337,1339,Far Cry 4,PS3,2014.0,Shooter,Ubisoft,0.33,0.79,0.08,0.23,1.44
1383,1385,Far Cry 2,PS3,2008.0,Action,Ubisoft,0.43,0.70,0.01,0.27,1.40
2106,2108,Far Cry 3,PC,2012.0,Shooter,Ubisoft,0.21,0.62,0.00,0.14,0.98
2119,2121,Far Cry 4,X360,2014.0,Shooter,Ubisoft,0.45,0.44,0.00,0.08,0.98
2434,2436,Far Cry: Primal,XOne,2016.0,Action,Ubisoft,0.46,0.32,0.00,0.07,0.85
3247,3249,Far Cry 4,PC,2014.0,Shooter,Ubisoft,0.15,0.42,0.00,0.05,0.62
3509,3511,Far Cry Instincts,XB,2005.0,Shooter,Ubisoft,0.32,0.24,0.00,0.02,0.57
4076,4078,Far Cry 2,PC,2008.0,Action,Ubisoft,0.01,0.45,0.00,0.03,0.49
6715,6717,Far Cry Instincts Predator,X360,2006.0,Shooter,Ubisoft,0.20,0.03,0.00,0.02,0.25
9250,9252,Far Cry: Primal,PC,2016.0,Action,Ubisoft,0.04,0.09,0.00,0.01,0.14
11441,11443,Far Cry Vengeance,Wii,2006.0,Shooter,Ubisoft,0.06,0.01,0.00,0.01,0.08
11709,11711,Far Cry Instincts Evolution,XB,2006.0,Shooter,Ubisoft,0.06,0.02,0.00,0.00,0.08
13250,13252,Far Cry,PC,2004.0,Shooter,Ubisoft,0.00,0.04,0.00,0.01,0.05

In [60]:
df[df["Name"].str.contains("Mario",na=False)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
11,12,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
...,...,...,...,...,...,...,...,...,...,...,...
12770,12772,Dance Dance Revolution: Mario Mix (JP sales),GC,2005.0,Simulation,Nintendo,0.00,0.00,0.05,0.00,0.06
13273,13275,Detective Conan: Marionette Symphony,3DS,2013.0,Adventure,Namco Bandai Games,0.00,0.00,0.05,0.00,0.05
15261,15264,Mario Tennis,3DS,NaN,Sports,NaN,0.00,0.00,0.02,0.00,0.02
16357,16360,Mario vs. Donkey Kong: Tipping Stars,WiiU,2015.0,Puzzle,Nintendo,0.00,0.00,0.01,0.00,0.01
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01

In [61]:
df['Total_regional_sales']=(df['NA_Sales']+df['EU_Sales']+df['JP_Sales'])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_regional_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,74.28
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,39.47
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,32.52
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,30.04
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,30.38
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0.00
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0.01

this is called as feature engineering

In [64]:
pivot=pd.pivot_table(
    df,
    index="Genre",
    values="Global_Sales",
    aggfunc="sum"
)

print(pivot)

              Global_Sales
Genre
Action             1751.18
Adventure           239.04
Fighting            448.91
Misc                809.96
Platform            831.37
Puzzle              244.95
Racing              732.04
Role-Playing        927.37
Shooter            1037.37
Simulation          392.20
Sports             1330.93
Strategy            175.12

this will summarize the total sales genre-wise