In [ ]:
numbers=[10,20,30,40,50]

mean=sum(numbers)/len(numbers)

print(mean)

30.0

In [ ]:
salaries=[20000,26000,24000,32000,35000,40000,200000]

#find the mean salary

In [ ]:
mean=sum(salaries)/len(salaries)

In [ ]:
print(mean)

53857.142857142855

In [ ]:
#mean can we affected by larger values

In [ ]:
#this willl lead us to median

In [ ]:
salaries=[20000,26000,24000,32000,35000,40000,200000]
#median means middle value here 32000 is the median

In [ ]:
#median the middle value but after sorting it only!!!

In [ ]:
num=[10,20,30,40]

#if the order is even then will pick middle numbers
#and we find the average
median=(num[1]+num[2])/2

print(median)

25.0

In [ ]:
#in python we have a library called statistics

In [ ]:
import statistics

In [ ]:
data=[10,20,30,40]
print(statistics.median(data))

25.0

In [ ]:
data1=[10,20,20,20,30,40,40,50]
# here 20 appears most
#so the mode will be 20 only!!!

In [ ]:
print(statistics.mode(data1))

20

In [ ]:
#blinkit or zomato these people they care about your most purchased product

In [ ]:
data2=[10,20,30,40,100,30,330,41,12,42,13]

In [ ]:
#find mean,median,mode

In [ ]:
print(statistics.mean(data2))
print(statistics.median(data2))
print(statistics.mode(data2))

60.72727272727273
30
30

In [ ]:
#these statistics will help us understand the numbers

In [ ]:
#ML also needs text data converted into numbers

In [ ]:
data=["mumbai","chennai","Goa","Kolkata"]

In [ ]:
print(statistics.mean(data))

TypeError: can't convert type 'str' to numerator/denominator

In [ ]:
#this one leads us to something called ENCODING

In [ ]:
#converting text into numbers

In [ ]:
import pandas as pd

data={
    "color":["red","blue",'Green','red','yellow','blue']
}

df=pd.DataFrame(data)
df

    color
0     red
1    blue
2   Green
3     red
4  yellow
5    blue

In [ ]:
#can ML understand this red/blue/yellow?

In [ ]:
#no it can understand why because machine understands only numbers!!

In [ ]:
#when you want to use one-hot encoding use this pandas function

#get_dummies

In [ ]:
pd.get_dummies(df['color'])

   Green   blue    red  yellow
0  False  False   True   False
1  False   True  False   False
2   True  False  False   False
3  False  False   True   False
4  False  False  False    True
5  False   True  False   False

In [ ]:
# why didnt we use like this
# red=1 blue=2 green=3

# red<blue<green

In [ ]:
#we can apply this one-hot encoding to city,gender,product category.department,branch

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path to dataset files: /kaggle/input/titanic-dataset

In [ ]:
path='/kaggle/input/titanic-dataset'
df=pd.read_csv(path+'/Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df[['Sex','Embarked',"Pclass"]].head()

      Sex Embarked  Pclass
0    male        S       3
1  female        C       1
2  female        S       3
3  female        S       1
4    male        S       3

In [ ]:
#can ML understand what is male and what is female??

In [ ]:
#no ml cant

In [ ]:
#ML likes only numbers....

In [ ]:
encoded=pd.get_dummies(df['Sex'])

In [ ]:
encoded2=pd.get_dummies(df[['Embarked','Pclass']])

In [ ]:
encoded2.head()

   Pclass  Embarked_C  Embarked_Q  Embarked_S
0       3       False       False        True
1       1        True       False       False
2       3       False       False        True
3       1       False       False        True
4       3       False       False        True

In [ ]:
df=pd.concat([df,encoded2],axis=1)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male,Pclass,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,True,3,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True,False,1,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False,3,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True,False,1,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,True,3,False,False,True

In [ ]:
encoded.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [ ]:
df=pd.concat([df,encoded],axis=1)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,True,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False,True
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,True

In [ ]:
df.drop("Sex",axis=1,inplace=True)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male,Pclass,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,False,True,3,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,True,False,1,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False,3,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,True,False,1,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,False,True,3,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,False,True,2,False,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,True,False,1,False,False,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,True,False,3,False,False,True
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,False,True,1,True,False,False
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,False,True,3,False,True,False

In [ ]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df=pd.concat([df,encoded2],axis=1)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,...,female,male,Pclass,Embarked_C,Embarked_Q,Embarked_S,Pclass,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,...,False,True,3,False,False,True,3,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,...,True,False,1,True,False,False,1,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,...,True,False,3,False,False,True,3,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,...,True,False,1,False,False,True,1,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,...,False,True,3,False,False,True,3,False,False,True

In [ ]:
print(df['Embarked'].unique())

['S' 'C' 'Q' nan]

In [ ]:
#number of one-hot encoded columns=number of unique categories

In [ ]:
df=pd.read_csv(path+"/Titanic-Dataset.csv")

In [ ]:
encoded_df=pd.get_dummies(
    df,
    columns=["Sex",'Embarked']
)
encoded_df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,False,True,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,True,False,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,True,False,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,True,False,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,False,True,False,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,True,False,False,False,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,True,False,False,False,True
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,False,True,True,False,False
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,False,True,False,True,False

In [ ]:
df['Pclass'].unique()

array([3, 1, 2])

In [ ]:
pd.get_dummies(df['Pclass'])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
encoded=pd.get_dummies(df['Embarked'])

encoded.sum()

C    168
Q     77
S    644
dtype: int64

In [ ]:
df=pd.read_csv(path+"/Titanic-Dataset.csv")
df_encoded=pd.get_dummies(df,columns=["Sex"])

In [ ]:
df_encoded.groupby("Survived")[["Sex_female","Sex_male"]].sum()

          Sex_female  Sex_male
Survived
0                 81       468
1                233       109

In [ ]:
#looking at it we can say female survived more in titanic

In [ ]:
df=pd.read_csv(path+"/Titanic-Dataset.csv")
df_encoded=pd.get_dummies(df["Embarked"])

df_encoded.sum()

C    168
Q     77
S    644
dtype: int64

In [ ]:
df=pd.read_csv(path+"/Titanic-Dataset.csv")

In [ ]:
df.shape

(891, 12)

In [ ]:
encoded_df=pd.get_dummies(df)

In [ ]:
encoded_df.shape

(891, 1731)

In [ ]:
encoded_df.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbing, Mr. Anthony","Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)",...,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2,1,1,38.0,1,0,71.2833,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,3,1,3,26.0,0,0,7.9250,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,4,1,1,35.0,1,0,53.1000,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,5,0,3,35.0,0,0,8.0500,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
#this is why feature count increases after encoding

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
pd.get_dummies(df['Sex'],drop_first=True)

      male
0     True
1    False
2    False
3    False
4     True
..     ...
886   True
887  False
888  False
889   True
890   True

[891 rows x 1 columns]

In [ ]:
#there is no need for second column

In [ ]:
# if gender has only 2 then we create both seperately or only single one (male/female)

In [ ]:
#comeback at 11:11 sharp

In [ ]:
data={
    "Age":[18,25,35,45,60],
    'salary':[20000,35000,45000,28000,90000]
}
df=pd.DataFrame(data)

In [ ]:
df

   Age  salary
0   18   20000
1   25   35000
2   35   45000
3   45   28000
4   60   90000

In [ ]:
#here salary is the larger value
#so salary will dominate the ml calculations

In [ ]:
# 45-60= 15

# 45000-90000=45000

# the larger column will always dominate

In [ ]:
#to come out of this we use feature scaling

In [ ]:
#MIN-MAX SCALING

In [ ]:
# we will shrink all values between 0 and 1

In [ ]:
# x`=((x-xmin)/(xmax-xmin))

In [ ]:
#scaling is nothing but bringing all the values to a same level
#if you scale properly all values will be in a single range

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaled_data=scaler.fit_transform(df)
print(scaled_data)

[[0.         0.        ]
 [0.16666667 0.21428571]
 [0.4047619  0.35714286]
 [0.64285714 0.11428571]
 [1.         1.        ]]

In [ ]:
#the minimum value here is 0
#and the maximum value is 1

In [ ]:
values=[100,200,300,400,500,600]
100/600
200/600
300/600
400/600
500/600
600/600

1.0

In [ ]:
#min max scaler helps you to compress the values

In [ ]:
scaled_df=pd.DataFrame(scaled_data,columns=df.columns)
print(scaled_df)

        Age    salary
0  0.000000  0.000000
1  0.166667  0.214286
2  0.404762  0.357143
3  0.642857  0.114286
4  1.000000  1.000000

In [ ]:
df

   Age  salary
0   18   20000
1   25   35000
2   35   45000
3   45   28000
4   60   90000

In [ ]:
scaled_df.min()

Age       0.0
salary    0.0
dtype: float64

In [ ]:
scaled_df.max()

Age       1.0
salary    1.0
dtype: float64

In [ ]:
#netflix might have watch hour from 1-1000 user ratings 1-5
#if we scale then we can compare them
#so, when we scale them then come range [0,1]

In [ ]:
data={
    "Marks":[100,200,300,400,500]
}

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaled=scaler.fit_transform(
    pd.DataFrame(data)
)
print(scaled)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]

In [ ]:
#next topic we have is standardscaler

In [ ]:
data={
    "Name":[
        "Ram",
        "sita",
        "RAM",
        None,
        "Krishna"
    ],
    "Gender":[
        "Male",
        "Female",
        "Male",
        "Female",
        "Male"
    ],
    "Dept":[
      "CSE",
      "ECE",
      "EEE",
      "ECE",
      "CSE"
    ],
    "Salary":[
        25000,
        30000,
        45000,
        75000,
        120000
    ],
    "JoinDate":[
        "2022-01-01",
        "2023-07-21",
        "2024-03-11",
        "2025-04-11",
        "2026-01-16"
    ]

}

df=pd.DataFrame(data)
df

      Name  Gender Dept  Salary    JoinDate
0      Ram    Male  CSE   25000  2022-01-01
1     sita  Female  ECE   30000  2023-07-21
2      RAM    Male  EEE   45000  2024-03-11
3     None  Female  ECE   75000  2025-04-11
4  Krishna    Male  CSE  120000  2026-01-16

In [ ]:
import pandas as pd

In [ ]:
data={
    "orderDate":[
        "2023-01-01",
        "2023-02-01",
        "2023-03-01",
        "2023-04-01",
    ],
    "sales":[
        1000,
        2000,
        3000,
        4900
    ]
}
df=pd.DataFrame(data)
df

    orderDate  sales
0  2023-01-01   1000
1  2023-02-01   2000
2  2023-03-01   3000
3  2023-04-01   4900

In [ ]:
df.dtypes

orderDate    object
sales         int64
dtype: object

In [ ]:
#here order date is a object(text)

In [ ]:
df['orderDate']=pd.to_datetime(df['orderDate'])
df.dtypes

orderDate    datetime64[ns]
sales                 int64
dtype: object

In [ ]:
#the reason to convert it to extract useful information

In [ ]:
df["Year"]=(df['orderDate'].dt.year)
df

   orderDate  sales  Year
0 2023-01-01   1000  2023
1 2023-02-01   2000  2023
2 2023-03-01   3000  2023
3 2023-04-01   4900  2023

In [ ]:
df['Month']=(df['orderDate'].dt.month)
df

   orderDate  sales  Year  Month
0 2023-01-01   1000  2023      1
1 2023-02-01   2000  2023      2
2 2023-03-01   3000  2023      3
3 2023-04-01   4900  2023      4

In [ ]:
df["monthName"]=(df['orderDate'].dt.month_name())
df

   orderDate  sales  Year  Month monthName
0 2023-01-01   1000  2023      1   January
1 2023-02-01   2000  2023      2  February
2 2023-03-01   3000  2023      3     March
3 2023-04-01   4900  2023      4     April

In [ ]:
df['Day']=(df["orderDate"].dt.day)
df

   orderDate  sales  Year  Month monthName  Day
0 2023-01-01   1000  2023      1   January    1
1 2023-02-01   2000  2023      2  February    1
2 2023-03-01   3000  2023      3     March    1
3 2023-04-01   4900  2023      4     April    1

In [ ]:
df['dayname']=(df['orderDate'].dt.day_name())
df

   orderDate  sales  Year  Month monthName  Day    dayname
0 2023-01-01   1000  2023      1   January    1     Sunday
1 2023-02-01   2000  2023      2  February    1  Wednesday
2 2023-03-01   3000  2023      3     March    1  Wednesday
3 2023-04-01   4900  2023      4     April    1   Saturday

In [ ]:
df['weekend']=(df["dayname"].isin(["Saturday","Sunday"]))

df

   orderDate  sales  Year  Month monthName  Day    dayname  weekend
0 2023-01-01   1000  2023      1   January    1     Sunday     True
1 2023-02-01   2000  2023      2  February    1  Wednesday    False
2 2023-03-01   3000  2023      3     March    1  Wednesday    False
3 2023-04-01   4900  2023      4     April    1   Saturday     True

In [ ]:


today=pd.Timestamp.today()

df["DaysSinceOrder"]=(today-df["orderDate"]).dt.days
df

,orderDate,sales,Year,Month,monthName,Day,dayname,weekend,DaysSinceOrder
0,2023-01-01,1000,2023,1,January,1,Sunday,True,1247
1,2023-02-01,2000,2023,2,February,1,Wednesday,False,1216
2,2023-03-01,3000,2023,3,March,1,Wednesday,False,1188
3,2023-04-01,4900,2023,4,April,1,Saturday,True,1157

In [ ]:
df.sort_values("orderDate")

,orderDate,sales,Year,Month,monthName,Day,dayname,weekend,DaysSinceOrder
0,2023-01-01,1000,2023,1,January,1,Sunday,True,1247
1,2023-02-01,2000,2023,2,February,1,Wednesday,False,1216
2,2023-03-01,3000,2023,3,March,1,Wednesday,False,1188
3,2023-04-01,4900,2023,4,April,1,Saturday,True,1157

In [ ]:
data={
    "JoiningDate":[
        "2022-01-10",
        "2023-03-03",
        "2012-02-22",
        "2025-09-09",
        "2016-01-01",
        "2018-03-04"
    ]
}

df=pd.DataFrame(data)
df

  JoiningDate
0  2022-01-10
1  2023-03-03
2  2012-02-22
3  2025-09-09
4  2016-01-01
5  2018-03-04

In [ ]:
df["JoiningDate"]=pd.to_datetime(df['JoiningDate'])

In [ ]:
df['Year']=(df['JoiningDate'].dt.year)

In [ ]:
df

  JoiningDate  Year
0  2022-01-10  2022
1  2023-03-03  2023
2  2012-02-22  2012
3  2025-09-09  2025
4  2016-01-01  2016
5  2018-03-04  2018

In [ ]:
df["monthname"]=(df['JoiningDate'].dt.month_name())
df

  JoiningDate  Year  monthname
0  2022-01-10  2022    January
1  2023-03-03  2023      March
2  2012-02-22  2012   February
3  2025-09-09  2025  September
4  2016-01-01  2016    January
5  2018-03-04  2018      March

In [ ]:
df["dayname"]=df["JoiningDate"].dt.day_name()

In [ ]:
df

  JoiningDate  Year  monthname    dayname
0  2022-01-10  2022    January     Monday
1  2023-03-03  2023      March     Friday
2  2012-02-22  2012   February  Wednesday
3  2025-09-09  2025  September    Tuesday
4  2016-01-01  2016    January     Friday
5  2018-03-04  2018      March     Sunday

In [ ]:
today=pd.Timestamp.today()

In [ ]:
df["dayswith"]=(today-df['JoiningDate']).dt.days
df

  JoiningDate  Year  monthname    dayname  dayswith
0  2022-01-10  2022    January     Monday      1603
1  2023-03-03  2023      March     Friday      1186
2  2012-02-22  2012   February  Wednesday      5213
3  2025-09-09  2025  September    Tuesday       265
4  2016-01-01  2016    January     Friday      3804
5  2018-03-04  2018      March     Sunday      3011