In [ ]:
data=[10,20,30,40,50]

#what is the mean of data?

In [ ]:
avg=(sum(data)/len(data))

In [ ]:
avg

30.0

In [ ]:
print(10-30)
print(20-30)
print(30-30)
print(40-30)
print(50-30)

-20
-10
0
10
20

In [ ]:
# positive and netagive will get cancel

400 100 0 100 400

In [ ]:
# if we add square of all those numbers we will get 1000

In [ ]:
#divide the entire value with 5(data points)

In [ ]:
1000/5

200.0

In [ ]:
# so here variance=200

In [ ]:
# variance is the sum of squared differece between the data points and the mean total divided by N(total number of datapoints)

In [ ]:
import numpy as np
data=[10,20,30,40,50]
print(np.var(data))

200.0

In [ ]:
import numpy as np
data=[20,20,20,20,20]
print(np.var(data))

0.0

In [ ]:
# you got variance as 200 what does this number mean???

In [ ]:
# variance squared values
# which are sometimes hard to understand
# we take square root thats standard deviation

In [ ]:
import numpy as np

data=[10,20,30,40,50]
print(np.std(data))

14.142135623730951

In [ ]:
data1=[30000,
31000,
29000,
30000,
30000]

data2=[
10000,
50000,
29000,
80000,
35000]

print(np.std(data1))
print(np.std(data2))

632.4555320336759
23421.357774475844

In [ ]:
# person 1 has the stable salary  why??
# why because the std is low for person 1

In [ ]:
marks=[
10,20,30,40,50,60,70,80,90,100
]
np.percentile(marks,90)

np.float64(91.0)

In [ ]:
np.percentile(data,50)

np.float64(30.0)

In [ ]:
np.percentile(data,75)

np.float64(40.0)

In [ ]:
np.percentile(data,25)

np.float64(20.0)

In [ ]:
# suppose 100 students wrote an exam
# /can we divide them into 4 equal groups???
# yes
#using quartiles
#we can have 4 equal parts
#pizza
#q1,q2,q3
marks=[
10,20,30,40,50,60,70,80,90,100
]
#what % of students scored below Q1
25
50

50

In [ ]:
5
10
15
20
25
30
35
40
45
50

50

In [ ]:
import pandas as pd

data=[10,20,30,40,500]

s=pd.Series(data)

s.skew()

np.float64(2.2206404584946937)

In [ ]:
data=[
    5,30,35,40,45,50,60,70,80,90,100
]
s=pd.Series(data)

s.skew()

np.float64(0.0)

In [ ]:
# skewness=0
#the data is balanced
# skewness>0
#the data is positive skrew
# skewness<0
#the data is negative skrew

In [ ]:
# why skewness is important?

# many ml algorithms assume balanced distributions

In [ ]:
# income data of employyes: positive skrew
# very few people earn very high salaries

In [ ]:
# exam marks are negative skrew
# when exam is easy

In [ ]:
#hospital bills because few patients have extremely expensive treatments

In [ ]:
data=[10,20,30,40,50,1000]

np.mean(data)

np.float64(191.66666666666666)

In [ ]:
#outliers can distort the mean
#outliers can distort the variance
#distort the std
#it can mislead the ML models

In [ ]:
# what we should be doing to get rid of these outliers?

In [ ]:
import numpy as np
data=[
    10,20,30,40,50,60,70,80,90,100,500
]

q1=np.percentile(data,25)
q3=np.percentile(data,75)

iqr=q3-q1

lower_bound=q1-(1.5*iqr)
upper_bound=q3+(1.5*iqr)

print("q1=",q1)
print("q3=",q3)
print("iqr=",iqr)
print("lower_bound=",lower_bound)
print("upper_bound=",upper_bound)

q1= 35.0
q3= 85.0
iqr= 50.0
lower_bound= -40.0
upper_bound= 160.0

In [ ]:
#in the data provided above there is an outlier

In [ ]:
for i in data:
  if i<lower_bound or i>upper_bound:
    print("Outlier",i)

Outlier 500

In [ ]:
import pandas as pd
s=pd.Series([
    10,20,30,40,50,60,70,80,90,100,500
])

q1=s.quantile(0.25)
q3=s.quantile(0.75)
iqr=q3-q1

lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
outliers=s[(s<lower_bound) | (s>upper_bound)]

print("list of outliers is :",outliers)

list of outliers is : 10    500
dtype: int64

In [ ]:
data=[
    15,20,30,40,33,35,37,99,60,55,120,450
]

In [ ]:
#should we remove the outlier??
#you might think to remove
#we should not removve it

In [ ]:
bank_transaction=[100,500,300,30000]
#this 30k is the one we might be looking for

In [ ]:
medical_results=[0,1,3,2,100]
#this value might be more valued/imp for out analysis

In [ ]:
#noise and outlier
#noise is some random error
#where as outlier is extreme value but valid observation

In [ ]:
#till now today we covered
#variance,standard deviation,percentiles,quartiles,skewness,outlier & detection

In [ ]:
import pandas as pd
marks={
    "Marks":[
        45,50,55,60,65,70,75,80,85,90
     ]
}

df=pd.DataFrame(marks)

df

   Marks
0     45
1     50
2     55
3     60
4     65
5     70
6     75
7     80
8     85
9     90

In [ ]:
df.describe()

           Marks
count  10.000000
mean   67.500000
std    15.138252
min    45.000000
25%    56.250000
50%    67.500000
75%    78.750000
max    90.000000

In [ ]:
df['Marks'].mean()

np.float64(67.5)

In [ ]:
df['Marks'].median()

67.5

In [ ]:
df['Marks'].mode()

0    45
1    50
2    55
3    60
4    65
5    70
6    75
7    80
8    85
9    90
Name: Marks, dtype: int64

In [ ]:
df['Marks'].var()

229.16666666666666

In [ ]:
df['Marks'].std()

15.138251770487457

In [ ]:
df['Marks'].min()

45

In [ ]:
df['Marks'].max()

90

In [ ]:
print(df['Marks'].max()-df['Marks'].min())

45

In [ ]:
#what does range tells us?
#range will tell us spread of the data

In [ ]:
df['Marks'].quantile(0.25)

np.float64(56.25)

In [ ]:
df['Marks'].quantile(0.50)

np.float64(67.5)

In [ ]:
df['Marks'].quantile(0.75)

np.float64(78.75)

In [ ]:
df['Marks'].skew()

np.float64(0.0)

In [ ]:
data={
    "maths":[45,55,65,75,85],
    "science":[50,60,70,80,90],
    "english":[40,50,60,70,80]
}
df=pd.DataFrame(data)

df

   maths  science  english
0     45       50       40
1     55       60       50
2     65       70       60
3     75       80       70
4     85       90       80

In [ ]:
print(df.describe())

           maths    science    english
count   5.000000   5.000000   5.000000
mean   65.000000  70.000000  60.000000
std    15.811388  15.811388  15.811388
min    45.000000  50.000000  40.000000
25%    55.000000  60.000000  50.000000
50%    65.000000  70.000000  60.000000
75%    75.000000  80.000000  70.000000
max    85.000000  90.000000  80.000000

In [ ]:
data={
    "salary":[
        25000,
        30000,
        40000,
        45000,
        55000,
        70000,
        75000,
        85000,
        100000
    ]
}
df=pd.DataFrame(data)

In [ ]:
#student performance analytics project

In [ ]:
import pandas as pd
import numpy as np
data={
    "student":[
        "A","B","C",'D','E','F','G','H','I','J','K','L','M','N','O'
    ],
    "marks":[45,55,58,60,70,75,78,82,85,88,90,92,95,98,250]
}

df=pd.DataFrame(data)

df

   student  marks
0        A     45
1        B     55
2        C     58
3        D     60
4        E     70
5        F     75
6        G     78
7        H     82
8        I     85
9        J     88
10       K     90
11       L     92
12       M     95
13       N     98
14       O    250

In [ ]:
mean_marks=df['marks'].mean()
median_marks=df['marks'].median()
mode_marks=df['marks'].mode()
print("Mean",mean_marks)
print("Median",median_marks)
print("Mode",mode_marks)

Mean 88.06666666666666
Median 82.0
Mode 0      45
1      55
2      58
3      60
4      70
5      75
6      78
7      82
8      85
9      88
10     90
11     92
12     95
13     98
14    250
Name: marks, dtype: int64

In [ ]:
variance=df['marks'].var()
std=df['marks'].std()

print("Variance",variance)
print("Standard Deviation",std)

Variance 2262.352380952381
Standard Deviation 47.56419221381123

In [ ]:
print("minimum marks",df["marks"].min())
print("maximum marks",df['marks'].max())

minimum marks 45
maximum marks 250

In [ ]:
range_marks=(
    df['marks'].max()-df['marks'].min()
)

In [ ]:
range_marks

205

In [ ]:
#lets find quartiles

In [ ]:
q1=df['marks'].quantile(0.25)
q2=df['marks'].quantile(0.50)
q3=df['marks'].quantile(0.75)

print("Q1",q1)
print("Q2",q2)
print("Q3",q3)

Q1 65.0
Q2 82.0
Q3 91.0

In [ ]:
iqr=q3-q1

print("iqr",iqr)

iqr 26.0

In [ ]:
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr

print("lower bound",lower_bound)
print("upper bound",upper_bound)

lower bound 26.0
upper bound 130.0

In [ ]:
outliers=df[(df['marks']<lower_bound) | (df['marks']>upper_bound)]

print(outliers)

   student  marks
14       O    250

In [ ]:
p25=np.percentile(df['marks'],25)
p50=np.percentile(df['marks'],50)
p75=np.percentile(df['marks'],75)
p90=np.percentile(df['marks'],90)

In [ ]:
skewness=df['marks'].skew()

In [ ]:
skewness

np.float64(3.1195183927122576)

In [ ]:
if skewness>0:
  print("positive skewed distribution")
elif skewness<0:
  print("negative skewed distribution")
else:
  print("normal distribution")

positive skewed distribution

In [ ]:
def category(mark):
  if mark>=90:
    return "excellent"
  elif mark>=75:
    return "good"
  elif mark>=60:
    return "average"
  else:
    return "needs improvement"

In [ ]:
df['category']=(df['marks'].apply(category))

df

   student  marks           category
0        A     45  needs improvement
1        B     55  needs improvement
2        C     58  needs improvement
3        D     60            average
4        E     70            average
5        F     75               good
6        G     78               good
7        H     82               good
8        I     85               good
9        J     88               good
10       K     90          excellent
11       L     92          excellent
12       M     95          excellent
13       N     98          excellent
14       O    250          excellent

In [ ]:
data={
    "student":[
        "ram",
        "sits",
        "ravi",
        'john',
        'krishna'
    ],
    "section":[
        "a",'b','a','b','a'
    ],
    'marks':[80,80,50,60,70]
}

df=pd.DataFrame(data)
df

   student section  marks
0      ram       a     80
1     sits       b     80
2     ravi       a     50
3     john       b     60
4  krishna       a     70

In [ ]:
df.groupby("section")['marks'].mean()

section
a    66.666667
b    70.000000
Name: marks, dtype: float64

In [ ]:
pivot=pd.pivot_table( df,
                     values="marks",
                      index='section',
                      aggfunc="sum"

)

pivot

         marks
section
a          200
b          140

In [ ]:
data={
    "branch":[
        "cse",
        "cse",
        "ece",
        "cse",
        "eee",
        "ece",
        "cse",
        "eee",
        "ece"
        ],
    "Gender":["male",
              "female",
              "male",
              "male",
              "female",
              "female",
              "female",
              "male",
              "female"],
    "marks":[
        80,90,60,50,60,70,88,77,60
    ]
}

df=pd.DataFrame(data)

In [ ]:
df

  branch  Gender  marks
0    cse    male     80
1    cse  female     90
2    ece    male     60
3    cse    male     50
4    eee  female     60
5    ece  female     70
6    cse  female     88
7    eee    male     77
8    ece  female     60

In [ ]:
pivot=pd.pivot_table(
    df,
    values="marks",
    index="branch",
    columns="Gender",
    aggfunc="mean"
)

In [ ]:
pivot

Gender  female  male
branch
cse       89.0  65.0
ece       65.0  60.0
eee       60.0  77.0