In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'students-performance-in-exams' dataset.
Path to dataset files: /kaggle/input/students-performance-in-exams

In [4]:
import pandas as pd
path="/kaggle/input/students-performance-in-exams"
df=pd.read_csv(path+"/StudentsPerformance.csv")

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
df.shape

(1000, 8)

In [8]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [9]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [11]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [13]:
df['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [14]:
df['reading score']

0      72
1      90
2      95
3      57
4      78
       ..
995    99
996    55
997    71
998    78
999    86
Name: reading score, Length: 1000, dtype: int64

In [15]:
df[['gender','lunch','math score']]

     gender         lunch  math score
0    female      standard          72
1    female      standard          69
2    female      standard          90
3      male  free/reduced          47
4      male      standard          76
..      ...           ...         ...
995  female      standard          88
996    male  free/reduced          62
997  female  free/reduced          59
998  female      standard          68
999  female  free/reduced          77

[1000 rows x 3 columns]

In [16]:
print(df['math score'].mean())

66.089

In [17]:
print(df['reading score'].mean())

69.169

In [18]:
print(df['math score'].max())

100

In [19]:
print(df['math score'].min())

0

In [20]:
print(df['math score'].std())

15.163080096009468

In [21]:
print(df['reading score'].var())

213.1656046046047

In [22]:
print(df['reading score'].median())

70.0

In [23]:
print(df['gender'].unique())

['female' 'male']

In [24]:
print(df['math score'].unique())

[ 72  69  90  47  76  71  88  40  64  38  58  65  78  50  18  46  54  66
  44  74  73  67  70  62  63  56  97  81  75  57  55  53  59  82  77  33
  52   0  79  39  45  60  61  41  49  30  80  42  27  43  68  85  98  87
  51  99  84  91  83  89  22 100  96  94  48  35  34  86  92  37  28  24
  26  95  36  29  32  93  19  23   8]

In [25]:
print(df['lunch'].unique())

['standard' 'free/reduced']

In [26]:
print(df['race/ethnicity'].unique())

['group B' 'group C' 'group A' 'group D' 'group E']

In [27]:
print(df['gender'].value_counts())

gender
female    518
male      482
Name: count, dtype: int64

In [28]:
print(df['lunch'].value_counts())

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

In [29]:
print(df['test preparation course'].value_counts)

<bound method IndexOpsMixin.value_counts of 0           none
1      completed
2           none
3           none
4           none
         ...
995    completed
996         none
997    completed
998    completed
999         none
Name: test preparation course, Length: 1000, dtype: object>

In [30]:
print(df[df['math score']>90])

     gender race/ethnicity parental level of education         lunch  \
34     male        group E                some college      standard
104    male        group C                some college      standard
114  female        group E           bachelor's degree      standard
121    male        group B          associate's degree      standard
149    male        group E          associate's degree  free/reduced
165  female        group C           bachelor's degree      standard
171    male        group E            some high school      standard
179  female        group D            some high school      standard
233    male        group E            some high school      standard
263  female        group E                 high school      standard
286    male        group E          associate's degree      standard
306    male        group E                some college      standard
451  female        group E                some college      standard
458  female        group E           bachelor's degree      standard
469    male        group C                some college      standard
501  female        group B          associate's degree      standard
503  female        group E          associate's degree      standard
521  female        group C          associate's degree      standard
539    male        group A          associate's degree      standard
546  female        group A            some high school      standard
562    male        group C           bachelor's degree      standard
566  female        group E           bachelor's degree  free/reduced
571    male        group A           bachelor's degree      standard
594  female        group C           bachelor's degree      standard
612    male        group C           bachelor's degree      standard
618    male        group D             master's degree      standard
623    male        group A                some college      standard
625    male        group D                some college      standard
685  female        group E             master's degree      standard
689    male        group E                some college  free/reduced
710    male        group C                some college      standard
712  female        group D                some college      standard
717  female        group C          associate's degree      standard
719    male        group E          associate's degree  free/reduced
736    male        group C          associate's degree      standard
779    male        group E          associate's degree      standard
784    male        group C           bachelor's degree      standard
815    male        group B            some high school      standard
846    male        group C             master's degree      standard
855  female        group B           bachelor's degree      standard
864    male        group C          associate's degree      standard
886  female        group E          associate's degree      standard
903  female        group D           bachelor's degree  free/reduced
916    male        group E           bachelor's degree      standard
919    male        group B                some college      standard
934    male        group C          associate's degree      standard
950    male        group E                 high school      standard
957  female        group D             master's degree      standard
962  female        group E          associate's degree      standard
979  female        group C          associate's degree      standard

    test preparation course  math score  reading score  writing score
34                     none          97             87             82
104               completed          98             86             90
114               completed          99            100            100
121               completed          91             89             92
149               completed         100            100             93
165               completed          96            100            100
171                    none          94             88             78
179               completed          97            100            100
233                    none          92             87             78
263                    none          99             93             90
286               completed          97             82             88
306               completed          99             87             81
451                    none         100             92             97
458                    none         100            100            100
469                    none          91             74             76
501               completed          94             87             92
503               completed          95             89             92
521                    none          91             86             84
539               completed          97             92             86
546               completed          92            100             97
562               completed          96             90             92
566               completed          92            100            100
571                    none          91             96             92
594               completed          92            100             99
612               completed          94             90             91
618                    none          95             81             84
623               completed         100             96             86
625               completed         100             97             99
685               completed          94             99            100
689                    none          93             90             83
710               completed          93             84             90
712                    none          98            100             99
717               completed          96             96             99
719               completed          91             73             80
736                    none          92             79             84
779               completed          94             85             82
784               completed          91             81             79
815               completed          94             86             87
846               completed          91             85             85
855                    none          97             97             96
864                    none          97             93             91
886               completed          93            100             95
903               completed          93            100            100
916               completed         100            100            100
919               completed          91             96             91
934               completed          98             87             90
950                    none          94             73             71
957                    none          92            100            100
962                    none         100            100            100
979                    none          91             95             94

In [31]:
print(df[df['reading score']>90])

     gender race/ethnicity parental level of education     lunch  \
2    female        group B             master's degree  standard
6    female        group B                some college  standard
102  female        group D          associate's degree  standard
106  female        group D             master's degree  standard
114  female        group E           bachelor's degree  standard
..      ...            ...                         ...       ...
957  female        group D             master's degree  standard
962  female        group E          associate's degree  standard
970  female        group D           bachelor's degree  standard
979  female        group C          associate's degree  standard
995  female        group E             master's degree  standard

    test preparation course  math score  reading score  writing score
2                      none          90             95             93
6                 completed          88             95             92
102                    none          85             91             89
106                    none          87            100            100
114               completed          99            100            100
..                      ...         ...            ...            ...
957                    none          92            100            100
962                    none         100            100            100
970                    none          89            100            100
979                    none          91             95             94
995               completed          88             99             95

[62 rows x 8 columns]

In [33]:
print(df['parental level of education'].unique())

["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

In [34]:
print(df['parental level of education'].value_counts())

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [35]:
print(df[df['gender']=='female'])

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
5    female        group B          associate's degree      standard
6    female        group B                some college      standard
..      ...            ...                         ...           ...
993  female        group D           bachelor's degree  free/reduced
995  female        group E             master's degree      standard
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
5                      none          71             83             78
6                 completed          88             95             92
..                      ...         ...            ...            ...
993                    none          62             72             74
995               completed          88             99             95
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[518 rows x 8 columns]

In [36]:
print(df[df['gender']=='male'])

    gender race/ethnicity parental level of education         lunch  \
3     male        group A          associate's degree  free/reduced
4     male        group C                some college      standard
7     male        group B                some college  free/reduced
8     male        group D                 high school  free/reduced
10    male        group C          associate's degree      standard
..     ...            ...                         ...           ...
985   male        group A                 high school      standard
987   male        group E            some high school      standard
990   male        group E                 high school  free/reduced
994   male        group A                 high school      standard
996   male        group C                 high school  free/reduced

    test preparation course  math score  reading score  writing score
3                      none          47             57             44
4                      none          76             78             75
7                      none          40             43             39
8                 completed          64             64             67
10                     none          58             54             52
..                      ...         ...            ...            ...
985                    none          57             51             54
987               completed          81             75             76
990               completed          86             81             75
994                    none          63             63             62
996                    none          62             55             55

[482 rows x 8 columns]

In [37]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("imdevskp/corona-virus-report")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'corona-virus-report' dataset.
Path to dataset files: /kaggle/input/corona-virus-report

In [38]:
path="/kaggle/input/corona-virus-report"

In [41]:
df=pd.read_csv(path+"/country_wise_latest.csv")

In [42]:
df.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [43]:
df.tail()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [44]:
df.shape

(187, 15)

In [45]:
print(df[df['Country/Region']=='India'])

   Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
79          India    1480073   33408     951166  495499      44457

    New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
79         637          33598                2.26                  64.26

    Deaths / 100 Recovered  Confirmed last week  1 week change  \
79                    3.51              1155338         324735

    1 week % increase       WHO Region
79              28.11  South-East Asia

In [46]:
print(df[df['Country/Region']=="India"]
      [["Confirmed","Deaths"]]

)

    Confirmed  Deaths
79    1480073   33408

In [47]:
india_data=df[df['Country/Region']=='India']

In [48]:
print(india_data[["Confirmed","Deaths"]])

    Confirmed  Deaths
79    1480073   33408

In [49]:
india_data=df[df['Country/Region']=="India"]

print("Total deaths in India")

print(india_data["Deaths"].sum())

Total deaths in India
33408

In [51]:
india_data=df[df['Country/Region']=='India']

In [54]:
print(india_data[["Country/Region","Confirmed","Deaths"]])

   Country/Region  Confirmed  Deaths
79          India    1480073   33408

In [55]:
import pandas as pd
data={
    "Country":["india","us","china",'india'],
    "confirmed":[1000,5000,2000,4000]
}
df=pd.DataFrame(data)
print(df[df["Country"]=='india'])

  Country  confirmed
0   india       1000
3   india       4000

In [56]:
print(df[df["confirmed"]>2000])

  Country  confirmed
1      us       5000
3   india       4000

In [57]:
print(df.groupby("Country")["confirmed"].sum())

Country
china    2000
india    5000
us       5000
Name: confirmed, dtype: int64

In [58]:
print(df.sort_values(
    "confirmed",
    ascending=False
))

  Country  confirmed
1      us       5000
3   india       4000
2   china       2000
0   india       1000

In [59]:
print(df.isnull().sum())

Country      0
confirmed    0
dtype: int64

In [60]:
df=pd.read_csv(path+"/country_wise_latest.csv")

In [64]:
india=df[df['Country/Region']=='India']

In [66]:
india

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia

In [67]:
print(india['Confirmed'].sum())

1480073

In [69]:
print(india['Deaths'].sum())

33408

In [70]:
print(india['Recovered'].sum())

951166

In [72]:
death_report=df.groupby(
    "Country/Region"
)[
    "Deaths"
].sum()
print(death_report)

Country/Region
Afghanistan           1269
Albania                144
Algeria               1163
Andorra                 52
Angola                  41
                      ...
West Bank and Gaza      78
Western Sahara           1
Yemen                  483
Zambia                 140
Zimbabwe                36
Name: Deaths, Length: 187, dtype: int64

In [73]:
print(death_report.sort_values(ascending=False).head(1))

Country/Region
US    148011
Name: Deaths, dtype: int64

In [75]:
death_report=df.groupby(
    "Country/Region"
)[
    "Deaths"
].sum()

In [76]:
print(death_report[death_report>10000])

Country/Region
Brazil             87618
France             30212
India              33408
Iran               15912
Italy              35112
Mexico             44022
Peru               18418
Russia             13334
Spain              28432
US                148011
United Kingdom     45844
Name: Deaths, dtype: int64

In [78]:
df['Active Cases']=(
    df["Confirmed"]
    -df['Deaths']
    -df["Recovered"]
)

print(df)

         Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0           Afghanistan      36263    1269      25198    9796        106
1               Albania       4880     144       2745    1991        117
2               Algeria      27973    1163      18837    7973        616
3               Andorra        907      52        803      52         10
4                Angola        950      41        242     667         18
..                  ...        ...     ...        ...     ...        ...
182  West Bank and Gaza      10621      78       3752    6791        152
183      Western Sahara         10       1          8       1          0
184               Yemen       1691     483        833     375         10
185              Zambia       4552     140       2815    1597         71
186            Zimbabwe       2704      36        542    2126        192

     New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0            10             18                3.50                  69.49
1             6             63                2.95                  56.25
2             8            749                4.16                  67.34
3             0              0                5.73                  88.53
4             1              0                4.32                  25.47
..          ...            ...                 ...                    ...
182           2              0                0.73                  35.33
183           0              0               10.00                  80.00
184           4             36               28.56                  49.26
185           1            465                3.08                  61.84
186           2             24                1.33                  20.04

     Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                      5.04                35526            737
1                      5.25                 4171            709
2                      6.17                23691           4282
3                      6.48                  884             23
4                     16.94                  749            201
..                      ...                  ...            ...
182                    2.08                 8916           1705
183                   12.50                   10              0
184                   57.98                 1619             72
185                    4.97                 3326           1226
186                    6.64                 1713            991

     1 week % increase             WHO Region  Active Cases
0                 2.07  Eastern Mediterranean          9796
1                17.00                 Europe          1991
2                18.07                 Africa          7973
3                 2.60                 Europe            52
4                26.84                 Africa           667
..                 ...                    ...           ...
182              19.12  Eastern Mediterranean          6791
183               0.00                 Africa             1
184               4.45  Eastern Mediterranean           375
185              36.86                 Africa          1597
186              57.85                 Africa          2126

[187 rows x 16 columns]

In [80]:
print(
    df.loc[0:5,["Country/Region","Confirmed"]]
)

        Country/Region  Confirmed
0          Afghanistan      36263
1              Albania       4880
2              Algeria      27973
3              Andorra        907
4               Angola        950
5  Antigua and Barbuda         86

In [81]:
print(df.iloc[0:5,0:3])

  Country/Region  Confirmed  Deaths
0    Afghanistan      36263    1269
1        Albania       4880     144
2        Algeria      27973    1163
3        Andorra        907      52
4         Angola        950      41

loc will be using the names

where as iloc will be using positions

In [82]:
df['Death Percentage']=(
    df["Deaths"]/df["Confirmed"]
)*100

print(df)

         Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0           Afghanistan      36263    1269      25198    9796        106
1               Albania       4880     144       2745    1991        117
2               Algeria      27973    1163      18837    7973        616
3               Andorra        907      52        803      52         10
4                Angola        950      41        242     667         18
..                  ...        ...     ...        ...     ...        ...
182  West Bank and Gaza      10621      78       3752    6791        152
183      Western Sahara         10       1          8       1          0
184               Yemen       1691     483        833     375         10
185              Zambia       4552     140       2815    1597         71
186            Zimbabwe       2704      36        542    2126        192

     New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0            10             18                3.50                  69.49
1             6             63                2.95                  56.25
2             8            749                4.16                  67.34
3             0              0                5.73                  88.53
4             1              0                4.32                  25.47
..          ...            ...                 ...                    ...
182           2              0                0.73                  35.33
183           0              0               10.00                  80.00
184           4             36               28.56                  49.26
185           1            465                3.08                  61.84
186           2             24                1.33                  20.04

     Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                      5.04                35526            737
1                      5.25                 4171            709
2                      6.17                23691           4282
3                      6.48                  884             23
4                     16.94                  749            201
..                      ...                  ...            ...
182                    2.08                 8916           1705
183                   12.50                   10              0
184                   57.98                 1619             72
185                    4.97                 3326           1226
186                    6.64                 1713            991

     1 week % increase             WHO Region  Active Cases  Death Percentage
0                 2.07  Eastern Mediterranean          9796          3.499435
1                17.00                 Europe          1991          2.950820
2                18.07                 Africa          7973          4.157581
3                 2.60                 Europe            52          5.733186
4                26.84                 Africa           667          4.315789
..                 ...                    ...           ...               ...
182              19.12  Eastern Mediterranean          6791          0.734394
183               0.00                 Africa             1         10.000000
184               4.45  Eastern Mediterranean           375         28.562980
185              36.86                 Africa          1597          3.075571
186              57.85                 Africa          2126          1.331361

[187 rows x 17 columns]

In [84]:
Country_report=df.groupby(
    "Country/Region"
)[
    "Death Percentage"
].sum()

In [85]:
print(Country_report.sort_values("Death Percentage",ascending=False).head())

TypeError: Series.sort_values() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given