numpy  pandas filtering sorting EDA    do companies give clean datasets

most of the  datasets are text   eg:  names,cities,product names,countries,emails...etc   all these are strings

In [1]:
name="Nikhil"
print(name.upper())

NIKHIL

In [2]:
city="hyderabad"
print(city.upper())

HYDERABAD

In [3]:
country="india"
print(country.upper())

INDIA

In [4]:
name="INDIA"
print(name.lower())

india

In [5]:
names=[
    "Nikhil",
    "nikhil",
    "NIkhIl",
    "NIKhil"
]
for name in names:
  print(name.lower())

nikhil
nikhil
nikhil
nikhil

In [7]:
name1="Nikhil"
name2="Nikhil"
print(name1==name2)

True

In [8]:
name="  Nikhil   "
print(name.strip())

Nikhil

In [9]:
text="I love BIRYANI"
print(text.replace("BIRYANI","Pizza"))

I love Pizza

In [10]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path to dataset files: /kaggle/input/titanic-dataset

In [11]:
path="/kaggle/input/titanic-dataset"
import pandas as pd
df=pd.read_csv(path+"/Titanic-Dataset.csv")

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df.shape

(891, 12)

In [14]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [15]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [16]:
df['Name']=df['Name'].str.upper()
df['Name'].head()

0                              BRAUND, MR. OWEN HARRIS
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                               HEIKKINEN, MISS. LAINA
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                             ALLEN, MR. WILLIAM HENRY
Name: Name, dtype: object

In [17]:
df['Name']=df['Name'].str.lower()
df['Name'].head()

0                              braund, mr. owen harris
1    cumings, mrs. john bradley (florence briggs th...
2                               heikkinen, miss. laina
3         futrelle, mrs. jacques heath (lily may peel)
4                             allen, mr. william henry
Name: Name, dtype: object

In [20]:
df[df["Name"].str.contains("mrs",case=False,na=False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"johnson, mrs. oscar w (elisabeth vilhelmina berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"nasser, mrs. nicholas (adele achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"hewlett, mrs. (mary d kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"beckwith, mrs. richard leonard (sallie monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"abelson, mrs. samuel (hannah wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"potter, mrs. thomas jr (lily alexenia wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"shelley, mrs. william (imanita parrish hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"rice, mrs. william (margaret norton)",female,39.0,0,5,382652,29.1250,NaN,Q

In [21]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
missing=df.isnull().sum()
print(missing.sort_values(ascending=False))

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

In [24]:
df['Age'].fillna(
    df['Age'].mean(),inplace=True
)
df

/tmp/ipykernel_1643/1315600030.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"braund, mr. owen harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"heikkinen, miss. laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"allen, mr. william henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"graham, miss. margaret edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"behr, mr. karl howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"dooley, mr. patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [25]:
df['Fare'].fillna(
    df['Fare'].median(),inplace=True
)

/tmp/ipykernel_1643/519147339.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(

In [26]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"braund, mr. owen harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"heikkinen, miss. laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"allen, mr. william henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"graham, miss. margaret edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"behr, mr. karl howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"dooley, mr. patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [27]:
df.drop("Cabin",axis=1,inplace=True)

In [28]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"braund, mr. owen harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"heikkinen, miss. laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"allen, mr. william henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"graham, miss. margaret edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"behr, mr. karl howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"dooley, mr. patrick",male,32.000000,0,0,370376,7.7500,Q

In [29]:
df['FamilySize']=(df['SibSp']+df["Parch"]+1)

In [30]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"braund, mr. owen harris",male,22.000000,1,0,A/5 21171,7.2500,S,2
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.000000,1,0,PC 17599,71.2833,C,2
2,3,1,3,"heikkinen, miss. laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S,1
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.000000,1,0,113803,53.1000,S,2
4,5,0,3,"allen, mr. william henry",male,35.000000,0,0,373450,8.0500,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.000000,0,0,211536,13.0000,S,1
887,888,1,1,"graham, miss. margaret edith",female,19.000000,0,0,112053,30.0000,S,1
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S,4
889,890,1,1,"behr, mr. karl howell",male,26.000000,0,0,111369,30.0000,C,1
890,891,0,3,"dooley, mr. patrick",male,32.000000,0,0,370376,7.7500,Q,1

In [31]:
df["isAlone"]=(df["FamilySize"]==1)

In [32]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,isAlone
0,1,0,3,"braund, mr. owen harris",male,22.000000,1,0,A/5 21171,7.2500,S,2,False
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.000000,1,0,PC 17599,71.2833,C,2,False
2,3,1,3,"heikkinen, miss. laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S,1,True
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.000000,1,0,113803,53.1000,S,2,False
4,5,0,3,"allen, mr. william henry",male,35.000000,0,0,373450,8.0500,S,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.000000,0,0,211536,13.0000,S,1,True
887,888,1,1,"graham, miss. margaret edith",female,19.000000,0,0,112053,30.0000,S,1,True
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S,4,False
889,890,1,1,"behr, mr. karl howell",male,26.000000,0,0,111369,30.0000,C,1,True
890,891,0,3,"dooley, mr. patrick",male,32.000000,0,0,370376,7.7500,Q,1,True

In [33]:
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,isAlone
0,1,0,3,"braund, mr. owen harris",male,22.000000,1,0,A/5 21171,7.2500,S,2,False
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.000000,1,0,PC 17599,71.2833,C,2,False
2,3,1,3,"heikkinen, miss. laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S,1,True
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.000000,1,0,113803,53.1000,S,2,False
4,5,0,3,"allen, mr. william henry",male,35.000000,0,0,373450,8.0500,S,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.000000,0,0,211536,13.0000,S,1,True
887,888,1,1,"graham, miss. margaret edith",female,19.000000,0,0,112053,30.0000,S,1,True
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S,4,False
889,890,1,1,"behr, mr. karl howell",male,26.000000,0,0,111369,30.0000,C,1,True
890,891,0,3,"dooley, mr. patrick",male,32.000000,0,0,370376,7.7500,Q,1,True

In [34]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
FamilySize       int64
isAlone           bool
dtype: object

In [36]:
df.astype('string')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,isAlone
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.25,S,2,False
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C,2,False
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.925,S,1,True
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1,S,2,False
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.05,S,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.0,0,0,211536,13.0,S,1,True
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0,S,1,True
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,29.69911764705882,1,2,W./C. 6607,23.45,S,4,False
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0,C,1,True
890,891,0,3,"dooley, mr. patrick",male,32.0,0,0,370376,7.75,Q,1,True

In [37]:
data={
    "OrderDate":[
        "2024-01-15",
        "2024-02-15",
        "2024-03-15",
        "2024-04-15",
        "2024-05-15"
    ]
}
df=pd.DataFrame(data)
df

    OrderDate
0  2024-01-15
1  2024-02-15
2  2024-03-15
3  2024-04-15
4  2024-05-15

In [38]:
df.dtypes

OrderDate    object
dtype: object

In [39]:
df['OrderDate']=pd.to_datetime(df['OrderDate'])
df.dtypes

OrderDate    datetime64[ns]
dtype: object

In [40]:
df['OrderDate'].dt.year

0    2024
1    2024
2    2024
3    2024
4    2024
Name: OrderDate, dtype: int32

In [41]:
df['OrderDate'].dt.month

0    1
1    2
2    3
3    4
4    5
Name: OrderDate, dtype: int32

In [42]:
df['OrderDate'].dt.day

0    15
1    15
2    15
3    15
4    15
Name: OrderDate, dtype: int32

In [43]:
df['OrderDate'].dt.day_name()

0       Monday
1     Thursday
2       Friday
3       Monday
4    Wednesday
Name: OrderDate, dtype: object

In [44]:
df['OrderDate'].dt.month_name()

0     January
1    February
2       March
3       April
4         May
Name: OrderDate, dtype: object

In [45]:
df['Year']=(df["OrderDate"].dt.year)
df['Month']=(df["OrderDate"].dt.month)
df

   OrderDate  Year  Month
0 2024-01-15  2024      1
1 2024-02-15  2024      2
2 2024-03-15  2024      3
3 2024-04-15  2024      4
4 2024-05-15  2024      5

In [46]:
today=pd.Timestamp.today()
today-df['OrderDate']

0   866 days 05:42:37.338585
1   835 days 05:42:37.338585
2   806 days 05:42:37.338585
3   775 days 05:42:37.338585
4   745 days 05:42:37.338585
Name: OrderDate, dtype: timedelta64[ns]

In [47]:
data={
    "birthdays":[
        "2000-08-15",
        "1997-02-15",
        "1999-03-15",
        "2001-04-15",
        "2002-05-15"
    ]
}
df=pd.DataFrame(data)
df

    birthdays
0  2000-08-15
1  1997-02-15
2  1999-03-15
3  2001-04-15
4  2002-05-15

In [48]:
df['birthdays']=pd.to_datetime(df['birthdays'])
df.dtypes

birthdays    datetime64[ns]
dtype: object

In [49]:
today=pd.Timestamp.today()
today

Timestamp('2026-05-30 05:48:30.200977')

In [50]:
today-df['birthdays']

0    9419 days 05:48:30.200977
1   10696 days 05:48:30.200977
2    9938 days 05:48:30.200977
3    9176 days 05:48:30.200977
4    8781 days 05:48:30.200977
Name: birthdays, dtype: timedelta64[ns]

In [51]:
data={
    "Marks":[35,77,56,54,98,70,77]
}
df=pd.DataFrame(data)
df

   Marks
0     35
1     77
2     56
3     54
4     98
5     70
6     77

In [54]:
def grades(mark):
  if mark>=50:
    return 'A'
  elif mark>=75:
    return 'B'
  elif mark>=60:
    return 'C'
  else:
    return 'D'
df['Grade']=(df['Marks'].apply(grades))

In [55]:
df

   Marks Grade
0     35     D
1     77     A
2     56     A
3     54     A
4     98     A
5     70     A
6     77     A

In [62]:
data={
    "Join_Date":[
        "2024-07-11",
        "2023-02-15",
        "2023-03-15",
        "2023-04-15",
    ]
}
df=pd.DataFrame(data)
df

    Join_Date
0  2024-07-11
1  2023-02-15
2  2023-03-15
3  2023-04-15

In [63]:
df["Join_Date"]=pd.to_datetime(df["Join_Date"])

In [64]:
today=pd.Timestamp.today()
df["Days_with_company"]=(
    today-
    df["Join_Date"]
    ).dt.days

In [65]:
df

   Join_Date  Days_with_company
0 2024-07-11                688
1 2023-02-15               1200
2 2023-03-15               1172
3 2023-04-15               1141

In [68]:
df_sorted=df.sort_values(by="Days_with_company",ascending=False)

In [69]:
df_sorted

   Join_Date  Days_with_company
1 2023-02-15               1200
2 2023-03-15               1172
3 2023-04-15               1141
0 2024-07-11                688

In [70]:
df["Join_Month"]=df["Join_Date"].dt.month_name()

df

   Join_Date  Days_with_company Join_Month
0 2024-07-11                688       July
1 2023-02-15               1200   February
2 2023-03-15               1172      March
3 2023-04-15               1141      April

In [71]:
data={

    "Cost":[
        100,200,500
    ],
    "Selling":[150,280,800]
}
df=pd.DataFrame(data)

df

   Cost  Selling
0   100      150
1   200      280
2   500      800

In [72]:
df['profit']=df['Selling']-df['Cost']

df

   Cost  Selling  profit
0   100      150      50
1   200      280      80
2   500      800     300

In [73]:
df["profit_percentage"]=df["profit"]/df["Cost"]*100

df

   Cost  Selling  profit  profit_percentage
0   100      150      50               50.0
1   200      280      80               40.0
2   500      800     300               60.0

In [74]:
df["high_profit"]=(df['profit']>50)

df

   Cost  Selling  profit  profit_percentage  high_profit
0   100      150      50               50.0        False
1   200      280      80               40.0         True
2   500      800     300               60.0         True

In [75]:
data={ "salary":[
    45000,
    55000,
    34000,
    41900,
    98000,
    56799,
    47469
]}

df=pd.DataFrame(data)

In [76]:
df

   salary
0   45000
1   55000
2   34000
3   41900
4   98000
5   56799
6   47469

In [77]:
def salary(x):
  if x<40000:
    return 'Low'
  elif x<60000:
    return "Medium"
  elif x<85000:
    return "High"
  elif x<100000:
    return "Very High"
df["Salary_category"]=df["salary"].apply(salary)
df

   salary Salary_category
0   45000          Medium
1   55000          Medium
2   34000             Low
3   41900          Medium
4   98000       Very High
5   56799          Medium
6   47469          Medium

In [78]:
data= {
    "Age":[22,23,24,25,26,27],
    "Income":[24000,43000,38000,68000,88000,76587]
}

df=pd.DataFrame(data)
df

   Age  Income
0   22   24000
1   23   43000
2   24   38000
3   25   68000
4   26   88000
5   27   76587

In [80]:
df['risk']=(df['Age']>60)

df

   Age  Income   risk
0   22   24000  False
1   23   43000  False
2   24   38000  False
3   25   68000  False
4   26   88000  False
5   27   76587  False

In [81]:
data={
    "Gender":["Male","Female","Male","Male","Female"]
}

In [82]:
df=pd.DataFrame(data)
df

   Gender
0    Male
1  Female
2    Male
3    Male
4  Female

there is a tool that converts text into numbers

In [83]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [84]:
from sklearn.preprocessing import LabelEncoder

In [85]:
le=LabelEncoder()

In [86]:
df['Gender']=le.fit_transform(df['Gender'])

In [87]:
df

   Gender
0       1
1       0
2       1
3       1
4       0

here  female-->0 and male-->1

In [88]:
data={
    "Department":[
        "CSE",
        "ECE",
        "EEE",
        "MECH",
        "CIVIL"
    ]
}

df=pd.DataFrame(data)
df

  Department
0        CSE
1        ECE
2        EEE
3       MECH
4      CIVIL

In [89]:
le=LabelEncoder()
df["Department"]=le.fit_transform(df["Department"])
df

   Department
0           1
1           2
2           3
3           4
4           0

In [90]:
print(
    dict(
        zip(
            le.classes_,
            le.transform(le.classes_)
        )
    )
)

{'CIVIL': np.int64(0), 'CSE': np.int64(1), 'ECE': np.int64(2), 'EEE': np.int64(3), 'MECH': np.int64(4)}

In [91]:
data={
    "City":[
        "Delhi",
        "Mumbai",
        "hyderabad",
        "chennai",
        "Delhi",
        "mumbai"
     ]
}

df=pd.DataFrame(data)
df

        City
0      Delhi
1     Mumbai
2  hyderabad
3    chennai
4      Delhi
5     mumbai

In [92]:
le=LabelEncoder()
df["City"]=le.fit_transform(df["City"])
df

   City
0     0
1     1
2     3
3     2
4     0
5     4

In [93]:
print(
    dict(
        zip(
            le.classes_,
            le.transform(le.classes_)
        )
    )
)

{'Delhi': np.int64(0), 'Mumbai': np.int64(1), 'chennai': np.int64(2), 'hyderabad': np.int64(3), 'mumbai': np.int64(4)}

delhi-->0

chennai-->2

2>0

chennai>delhi

In [96]:
data = {
    "Name":[
        "Ram",
        "Shyam",
        "Mohan",
        "ramesh",
        None
    ],
    "Gender":[
        "Male",
        "Male",
        "Male",
        "Male",
        "Female"
    ],
    "JoinDate":[
        "2022-01-01",
        "2022-02-01",
        "2022-03-01",
        "2022-04-01",
        "2022-05-01"
    ]
}

df=pd.DataFrame(data)
df

     Name  Gender    JoinDate
0     Ram    Male  2022-01-01
1   Shyam    Male  2022-02-01
2   Mohan    Male  2022-03-01
3  ramesh    Male  2022-04-01
4    None  Female  2022-05-01

In [98]:
df['Name']=(df['Name'].str.upper().str.strip())
df

     Name  Gender    JoinDate
0     RAM    Male  2022-01-01
1   SHYAM    Male  2022-02-01
2   MOHAN    Male  2022-03-01
3  RAMESH    Male  2022-04-01
4    None  Female  2022-05-01

In [99]:
df['Name']=(
    df["Name"]
.fillna("Unknown person")
)

df

             Name  Gender    JoinDate
0             RAM    Male  2022-01-01
1           SHYAM    Male  2022-02-01
2           MOHAN    Male  2022-03-01
3          RAMESH    Male  2022-04-01
4  Unknown person  Female  2022-05-01

In [100]:
df['JoinDate']=(pd.to_datetime(df['JoinDate']))
df

             Name  Gender   JoinDate
0             RAM    Male 2022-01-01
1           SHYAM    Male 2022-02-01
2           MOHAN    Male 2022-03-01
3          RAMESH    Male 2022-04-01
4  Unknown person  Female 2022-05-01

In [101]:
df['Year']=df['JoinDate'].dt.year
df

             Name  Gender   JoinDate  Year
0             RAM    Male 2022-01-01  2022
1           SHYAM    Male 2022-02-01  2022
2           MOHAN    Male 2022-03-01  2022
3          RAMESH    Male 2022-04-01  2022
4  Unknown person  Female 2022-05-01  2022

In [102]:
le=LabelEncoder()
df["Gender"]=(le.fit_transform(df["Gender"]))
df

             Name  Gender   JoinDate  Year
0             RAM       1 2022-01-01  2022
1           SHYAM       1 2022-02-01  2022
2           MOHAN       1 2022-03-01  2022
3          RAMESH       1 2022-04-01  2022
4  Unknown person       0 2022-05-01  2022

here male -->1 and female -->0

what is data wrangling
why is string processing important
why convert dates?
difference between object and datetime
why handle missing values and how?
feature engineering
scikit-learn
encoding
label encoding
limitation of label encoding(that assumes based on numbers which is greater)